# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class PayoutMethods(BaseModel):
    """
    payout_methods object
    """ # noqa: E501
    account_name: Optional[StrictStr] = None
    account_number: Optional[StrictStr] = None
    auto_withdrawal_day: Optional[Union[StrictFloat, StrictInt]] = None
    auto_withdrawal_enabled: Optional[StrictBool] = None
    auto_withdrawal_last_run: Optional[StrictStr] = None
    auto_withdrawal_method: Optional[StrictStr] = None
    auto_withdrawal_mobile_provider: Optional[StrictStr] = None
    bank_code: Optional[StrictStr] = None
    bank_name: Optional[StrictStr] = None
    branch_code: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    is_default: Optional[StrictBool] = None
    is_spi_enabled: Optional[StrictBool] = None
    is_uemoa: Optional[StrictBool] = None
    is_valid: Optional[StrictBool] = None
    organization_id: Optional[UUID] = None
    payout_method_id: Optional[UUID] = None
    payout_method_type: Optional[StrictStr] = None
    spi_account_number: Optional[StrictStr] = None
    spi_alias_mbno: Optional[StrictStr] = None
    spi_alias_shid: Optional[StrictStr] = None
    spi_alias_type: Optional[StrictStr] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["account_name", "account_number", "auto_withdrawal_day", "auto_withdrawal_enabled", "auto_withdrawal_last_run", "auto_withdrawal_method", "auto_withdrawal_mobile_provider", "bank_code", "bank_name", "branch_code", "country", "created_at", "is_default", "is_spi_enabled", "is_uemoa", "is_valid", "organization_id", "payout_method_id", "payout_method_type", "spi_account_number", "spi_alias_mbno", "spi_alias_shid", "spi_alias_type", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PayoutMethods from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PayoutMethods from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_name": obj.get("account_name"),
            "account_number": obj.get("account_number"),
            "auto_withdrawal_day": obj.get("auto_withdrawal_day"),
            "auto_withdrawal_enabled": obj.get("auto_withdrawal_enabled"),
            "auto_withdrawal_last_run": obj.get("auto_withdrawal_last_run"),
            "auto_withdrawal_method": obj.get("auto_withdrawal_method"),
            "auto_withdrawal_mobile_provider": obj.get("auto_withdrawal_mobile_provider"),
            "bank_code": obj.get("bank_code"),
            "bank_name": obj.get("bank_name"),
            "branch_code": obj.get("branch_code"),
            "country": obj.get("country"),
            "created_at": obj.get("created_at"),
            "is_default": obj.get("is_default"),
            "is_spi_enabled": obj.get("is_spi_enabled"),
            "is_uemoa": obj.get("is_uemoa"),
            "is_valid": obj.get("is_valid"),
            "organization_id": obj.get("organization_id"),
            "payout_method_id": obj.get("payout_method_id"),
            "payout_method_type": obj.get("payout_method_type"),
            "spi_account_number": obj.get("spi_account_number"),
            "spi_alias_mbno": obj.get("spi_alias_mbno"),
            "spi_alias_shid": obj.get("spi_alias_shid"),
            "spi_alias_type": obj.get("spi_alias_type"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


