# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class Subscriptions(BaseModel):
    """
    subscriptions object
    """ # noqa: E501
    created_at: Optional[datetime] = None
    created_by: Optional[StrictStr] = None
    customer_id: Optional[UUID] = None
    end_date: Optional[StrictStr] = None
    environment: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    next_billing_date: Optional[StrictStr] = None
    organization_id: Optional[UUID] = None
    price_id: Optional[UUID] = None
    product_id: Optional[UUID] = None
    start_date: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    subscription_id: Optional[UUID] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["created_at", "created_by", "customer_id", "end_date", "environment", "metadata", "next_billing_date", "organization_id", "price_id", "product_id", "start_date", "status", "subscription_id", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subscriptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subscriptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "customer_id": obj.get("customer_id"),
            "end_date": obj.get("end_date"),
            "environment": obj.get("environment"),
            "metadata": obj.get("metadata"),
            "next_billing_date": obj.get("next_billing_date"),
            "organization_id": obj.get("organization_id"),
            "price_id": obj.get("price_id"),
            "product_id": obj.get("product_id"),
            "start_date": obj.get("start_date"),
            "status": obj.get("status"),
            "subscription_id": obj.get("subscription_id"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


