/*
lomi. API

Testing BeneficiaryPayoutAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lomisdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/lomiafrica/lomi-go-sdk"
)

func Test_lomisdk_BeneficiaryPayoutAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BeneficiaryPayoutAPIService BeneficiaryPayoutsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BeneficiaryPayoutAPI.BeneficiaryPayoutsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BeneficiaryPayoutAPIService BeneficiaryPayoutsPayoutIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var payoutId string

		resp, httpRes, err := apiClient.BeneficiaryPayoutAPI.BeneficiaryPayoutsPayoutIdGet(context.Background(), payoutId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BeneficiaryPayoutAPIService BeneficiaryPayoutsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BeneficiaryPayoutAPI.BeneficiaryPayoutsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
