/*
lomi. API

Testing SPIAccountAliasesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lomisdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/lomiafrica/lomi-go-sdk"
)

func Test_lomisdk_SPIAccountAliasesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SPIAccountAliasesAPIService ListSpiAccountAliases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SPIAccountAliasesAPI.ListSpiAccountAliases(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SPIAccountAliasesAPIService RetrieveSpiAccountAliase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aliasId string

		resp, httpRes, err := apiClient.SPIAccountAliasesAPI.RetrieveSpiAccountAliase(context.Background(), aliasId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
