/*
lomi. API

Testing UsageBillingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lomisdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/lomiafrica/lomi-go-sdk"
)

func Test_lomisdk_UsageBillingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UsageBillingAPIService CreateMeter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UsageBillingAPI.CreateMeter(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsageBillingAPIService DeleteMeter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var meterId string

		httpRes, err := apiClient.UsageBillingAPI.DeleteMeter(context.Background(), meterId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsageBillingAPIService ListMeterBalances", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UsageBillingAPI.ListMeterBalances(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsageBillingAPIService ListMeters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UsageBillingAPI.ListMeters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsageBillingAPIService RetrieveMeter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var meterId string

		resp, httpRes, err := apiClient.UsageBillingAPI.RetrieveMeter(context.Background(), meterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsageBillingAPIService RetrieveMeterBalance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var balanceId string

		resp, httpRes, err := apiClient.UsageBillingAPI.RetrieveMeterBalance(context.Background(), balanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsageBillingAPIService UpdateMeter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var meterId string

		resp, httpRes, err := apiClient.UsageBillingAPI.UpdateMeter(context.Background(), meterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
