export const Constants = {
  public: {
    Enums: {
      aggregation_function: ['count', 'sum', 'avg', 'min', 'max', 'unique'],
      billing_interval: [
        'day',
        'week',
        'bi-weekly',
        'month',
        'bi-monthly',
        'quarterly',
        'semi-annual',
        'year',
        'lifetime',
        'unit',
      ],
      bnpl_fee_type: [
        'merchant_processing',
        'customer_interest',
        'platform_risk',
        'late_fee',
      ],
      bnpl_status: ['pending', 'collected', 'waived', 'refunded'],
      checkout_session_status: ['open', 'completed', 'expired'],
      cli_device_request_status: [
        'pending',
        'approved',
        'denied',
        'expired',
        'completed',
      ],
      conversion_type: ['payment', 'withdrawal', 'refund', 'manual'],
      currency_code: ['XOF', 'USD', 'EUR'],
      customer_type: ['all', 'new', 'returning'],
      discount_type: ['percentage', 'fixed'],
      dispute_status: ['pending', 'resolved', 'closed'],
      entity_type: ['merchant', 'organization', 'platform'],
      event_type: [
        'validate_api_key',
        'create_api_key',
        'edit_api_key',
        'remove_api_key',
        'user_login',
        'edit_user_password',
        'create_pin',
        'edit_pin',
        'edit_user_details',
        'authorize_user_2fa',
        'create_user_2fa',
        'remove_user_2fa',
        'edit_user_phone',
        'set_callback_url',
        'update_webhook',
        'add_bank_account',
        'remove_bank_account',
        'create_payout',
        'beneficiary_payout_created',
        'mass_beneficiary_payout_created',
        'payout_status_change',
        'process_payment',
        'payment_status_change',
        'create_refund',
        'refund_status_change',
        'create_dispute',
        'dispute_status_change',
        'list_checkout_sessions',
        'update_subscription_plan',
        'create_subscription',
        'cancel_subscription',
        'subscription_status_change',
        'subscription_payment_failed',
        'archive_plan',
        'create_product',
        'update_product',
        'delete_product',
        'archive_product',
        'provider_status_change',
        'provider_connection_error',
        'provider_integration_success',
        'system_maintenance',
        'system_update',
        'compliance_update',
        'api_status_change',
        'kyc_status_auto_updated',
        'kyc_documents_submitted',
        'customer_verification_required',
        'customer_verification_success',
        'customer_verification_failed',
      ],
      failed_payment_action: ['cancel', 'pause', 'continue'],
      fee_category: ['payment_processing', 'payout', 'other'],
      fee_payer_type: ['merchant', 'customer', 'platform'],
      fee_subcategory: [
        'pos',
        'bnpl',
        'cards',
        'mobile_money',
        'bank_transfer_local',
        'bank_transfer_international',
        'bank_transfer_beneficiary',
        'mobile_money_payout',
        'mobile_money_beneficiary',
        'refund',
        'partial_refund',
        'chargeback',
        'currency_conversion',
        'international_cards',
        'subscription_payments',
      ],
      fee_type: ['platform', 'processing', 'conversion', 'payout', 'refund'],
      feedback_status: ['open', 'reviewed', 'implemented', 'closed'],
      filter_operator: [
        'eq',
        'ne',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'not_like',
      ],
      first_payment_type: ['initial', 'non_initial', 'prorated'],
      fraud_action: ['flag', 'block'],
      fraud_alert_status: ['flagged', 'blocked', 'resolved', 'dismissed'],
      fraud_rule_type: ['velocity', 'threshold', 'watchlist'],
      invoice_status: ['sent', 'paid', 'overdue', 'cancelled'],
      kyc_status: [
        'not_submitted',
        'pending',
        'not_authorized',
        'approved',
        'rejected',
        'starter_business',
      ],
      link_type: ['instant', 'product'],
      member_role: ['Admin', 'Member'],
      notification_type: [
        'onboarding',
        'tip',
        'transaction',
        'payout',
        'provider_status',
        'alert',
        'billing',
        'compliance',
        'update',
        'security_alert',
        'maintenance',
        'dispute',
        'refund',
        'invoice',
        'subscription',
        'webhook',
        'chargeback',
      ],
      onboarding_status: [
        'pending',
        'completed',
        'failed',
        'skipped',
        'in_progress',
      ],
      organization_status: ['active', 'inactive', 'suspended'],
      organization_verification_status: ['unverified', 'starter', 'verified'],
      payment_method_code: [
        'CARDS',
        'MOBILE_MONEY',
        'BANK_TRANSFER',
        'BNPL',
        'FREE',
      ],
      payout_status: ['pending', 'processing', 'completed', 'failed'],
      permission_action: ['view', 'create', 'edit', 'delete', 'approve'],
      permission_category: [
        'payments',
        'accounts',
        'products',
        'subscriptions',
        'customers',
      ],
      pricing_model: ['standard', 'pay_what_you_want', 'tiered', 'volume'],
      product_type: ['one_time', 'recurring', 'usage_based'],
      provider_business_type: ['fintech', 'other'],
      provider_code: [
        'WAVE',
        'JUMBO',
        'MTN',
        'STRIPE',
        'SPI',
        'CYBERSOURCE',
        'FREE',
      ],
      provider_payment_status: [
        'processing',
        'cancelled',
        'succeeded',
        'expired',
        'refunded',
      ],
      qr_code_type: ['static', 'dynamic'],
      reconciliation_status: [
        'pending',
        'matched',
        'partial_match',
        'mismatch',
        'resolved',
      ],
      refund_status: ['pending', 'completed', 'failed'],
      spi_account_status: ['OUVERT', 'BLOQUE', 'CLOTURE'],
      spi_account_type: [
        'CACC',
        'CARD',
        'CASH',
        'CHAR',
        'CISH',
        'CURR',
        'DPST',
        'SVGS',
        'ULAA',
      ],
      spi_alias_type: ['SHID', 'MBNO', 'MCOD'],
      spi_document_type: [
        'CINV',
        'CMCN',
        'DISP',
        'PUOR',
        'CONT',
        'INVC',
        'PMNT',
        'TPMT',
      ],
      spi_payment_category: [
        '631',
        '000',
        '400',
        '733',
        '300',
        '999',
        '500',
        '521',
        '401',
      ],
      spi_payment_flow_type: [
        'BANK_TO_BANK',
        'BANK_TO_WALLET',
        'WALLET_TO_BANK',
        'WALLET_TO_WALLET',
        'INTRA_ACCOUNT',
      ],
      spi_payment_request_category: ['500', '521', '401'],
      spi_payment_status: ['INITIE', 'ENVOYE', 'IRREVOCABLE', 'REJETE'],
      spi_rejection_reason: [
        'BE23',
        'DU03',
        'AC04',
        'AC06',
        'AEXR',
        'AG03',
        'AG10',
        'AG11',
        'ALAC',
        'AM02',
        'AM09',
        'AM14',
        'APAR',
        'RR07',
        'FR01',
        'AB03',
        'AB04',
        'AB08',
        'AB09',
        'AC03',
        'AG01',
        'AM04',
        'RR04',
        'CUST',
        'ARDT',
      ],
      spi_webhook_event_code: [
        'PAIEMENT_RECU',
        'PAIEMENT_ENVOYE',
        'PAIEMENT_REJETE',
        'RTP_RECU',
        'RTP_REJETE',
        'RETOUR_ENVOYE',
        'RETOUR_REJETE',
        'RETOUR_RECU',
        'ANNULATION_DEMANDE',
        'ANNULATION_REJETE',
      ],
      subscription_status: [
        'pending',
        'active',
        'paused',
        'cancelled',
        'expired',
        'past_due',
        'trial',
      ],
      support_category: ['account', 'billing', 'technical', 'feature', 'other'],
      support_priority: ['low', 'normal', 'high', 'urgent'],
      support_status: ['open', 'in_progress', 'resolved', 'closed'],
      team_status: ['active', 'invited', 'inactive'],
      ticket_status: ['open', 'resolved', 'closed'],
      transaction_status: [
        'pending',
        'completed',
        'failed',
        'refunded',
        'expired',
      ],
      transaction_type: ['payment', 'instalment'],
      usage_aggregation: ['sum', 'max', 'last_during_period', 'last_ever'],
      usage_frequency: [
        'total',
        'per_customer',
        'per_day',
        'per_week',
        'per_month',
      ],
      webhook_event: [
        'PAYMENT_CREATED',
        'PAYMENT_SUCCEEDED',
        'PAYMENT_FAILED',
        'PAYMENT_CANCELED',
        'REFUND_CREATED',
        'REFUND_COMPLETED',
        'REFUND_FAILED',
        'SUBSCRIPTION_CREATED',
        'SUBSCRIPTION_RENEWED',
        'SUBSCRIPTION_CANCELED',
        'CHECKOUT_COMPLETED',
        'PROVIDER_STATUS_CHANGED',
      ],
    },
  },
} as const;
