export { FacebookIcon } from './FacebookIcon';
export { GitHubIcon } from './GitHubIcon';
export { GlobeIcon } from './GlobeIcon';
export { InstagramIcon } from './InstagramIcon';
export { JumboIcon } from './JumboIcon';
export { LinkedInIcon } from './LinkedInIcon';
export { WhatsappIcon } from './WhatsappIcon';
export { XIcon } from './XIcon';
export { SlackIcon } from './SlackIcon';
