/*
lomi. API

Payment processing API for francophone West African businesses.

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
)

// checks if the PayoutsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutsUpdate{}

// PayoutsUpdate Request body for updating a payouts object. Only include fields you want to modify.
type PayoutsUpdate struct {
	// Unique identifier (UUID format)
	AccountId *string `json:"account_id,omitempty"`
	// Amount in the smallest currency unit (e.g., cents for USD, same for XOF)
	Amount *float64 `json:"amount,omitempty"`
	// Three-letter ISO currency code (e.g., XOF, USD, EUR)
	CurrencyCode *string `json:"currency_code,omitempty"`
	// Set of key-value pairs for storing additional information
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	PaymentMethodCode *string `json:"payment_method_code,omitempty"`
	// Unique identifier (UUID format)
	PayoutId *string `json:"payout_id,omitempty"`
	// Unique identifier (UUID format)
	PayoutMethodId *string `json:"payout_method_id,omitempty"`
	ProviderCode *string `json:"provider_code,omitempty"`
	// Current status of the resource
	Status *string `json:"status,omitempty"`
}

// NewPayoutsUpdate instantiates a new PayoutsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutsUpdate() *PayoutsUpdate {
	this := PayoutsUpdate{}
	return &this
}

// NewPayoutsUpdateWithDefaults instantiates a new PayoutsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutsUpdateWithDefaults() *PayoutsUpdate {
	this := PayoutsUpdate{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *PayoutsUpdate) SetAccountId(v string) {
	o.AccountId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetAmount() float64 {
	if o == nil || IsNil(o.Amount) {
		var ret float64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float64 and assigns it to the Amount field.
func (o *PayoutsUpdate) SetAmount(v float64) {
	o.Amount = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *PayoutsUpdate) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PayoutsUpdate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPaymentMethodCode returns the PaymentMethodCode field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetPaymentMethodCode() string {
	if o == nil || IsNil(o.PaymentMethodCode) {
		var ret string
		return ret
	}
	return *o.PaymentMethodCode
}

// GetPaymentMethodCodeOk returns a tuple with the PaymentMethodCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetPaymentMethodCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethodCode) {
		return nil, false
	}
	return o.PaymentMethodCode, true
}

// HasPaymentMethodCode returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasPaymentMethodCode() bool {
	if o != nil && !IsNil(o.PaymentMethodCode) {
		return true
	}

	return false
}

// SetPaymentMethodCode gets a reference to the given string and assigns it to the PaymentMethodCode field.
func (o *PayoutsUpdate) SetPaymentMethodCode(v string) {
	o.PaymentMethodCode = &v
}

// GetPayoutId returns the PayoutId field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetPayoutId() string {
	if o == nil || IsNil(o.PayoutId) {
		var ret string
		return ret
	}
	return *o.PayoutId
}

// GetPayoutIdOk returns a tuple with the PayoutId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetPayoutIdOk() (*string, bool) {
	if o == nil || IsNil(o.PayoutId) {
		return nil, false
	}
	return o.PayoutId, true
}

// HasPayoutId returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasPayoutId() bool {
	if o != nil && !IsNil(o.PayoutId) {
		return true
	}

	return false
}

// SetPayoutId gets a reference to the given string and assigns it to the PayoutId field.
func (o *PayoutsUpdate) SetPayoutId(v string) {
	o.PayoutId = &v
}

// GetPayoutMethodId returns the PayoutMethodId field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetPayoutMethodId() string {
	if o == nil || IsNil(o.PayoutMethodId) {
		var ret string
		return ret
	}
	return *o.PayoutMethodId
}

// GetPayoutMethodIdOk returns a tuple with the PayoutMethodId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetPayoutMethodIdOk() (*string, bool) {
	if o == nil || IsNil(o.PayoutMethodId) {
		return nil, false
	}
	return o.PayoutMethodId, true
}

// HasPayoutMethodId returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasPayoutMethodId() bool {
	if o != nil && !IsNil(o.PayoutMethodId) {
		return true
	}

	return false
}

// SetPayoutMethodId gets a reference to the given string and assigns it to the PayoutMethodId field.
func (o *PayoutsUpdate) SetPayoutMethodId(v string) {
	o.PayoutMethodId = &v
}

// GetProviderCode returns the ProviderCode field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetProviderCode() string {
	if o == nil || IsNil(o.ProviderCode) {
		var ret string
		return ret
	}
	return *o.ProviderCode
}

// GetProviderCodeOk returns a tuple with the ProviderCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetProviderCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderCode) {
		return nil, false
	}
	return o.ProviderCode, true
}

// HasProviderCode returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasProviderCode() bool {
	if o != nil && !IsNil(o.ProviderCode) {
		return true
	}

	return false
}

// SetProviderCode gets a reference to the given string and assigns it to the ProviderCode field.
func (o *PayoutsUpdate) SetProviderCode(v string) {
	o.ProviderCode = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PayoutsUpdate) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutsUpdate) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PayoutsUpdate) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PayoutsUpdate) SetStatus(v string) {
	o.Status = &v
}

func (o PayoutsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currency_code"] = o.CurrencyCode
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.PaymentMethodCode) {
		toSerialize["payment_method_code"] = o.PaymentMethodCode
	}
	if !IsNil(o.PayoutId) {
		toSerialize["payout_id"] = o.PayoutId
	}
	if !IsNil(o.PayoutMethodId) {
		toSerialize["payout_method_id"] = o.PayoutMethodId
	}
	if !IsNil(o.ProviderCode) {
		toSerialize["provider_code"] = o.ProviderCode
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullablePayoutsUpdate struct {
	value *PayoutsUpdate
	isSet bool
}

func (v NullablePayoutsUpdate) Get() *PayoutsUpdate {
	return v.value
}

func (v *NullablePayoutsUpdate) Set(val *PayoutsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutsUpdate(val *PayoutsUpdate) *NullablePayoutsUpdate {
	return &NullablePayoutsUpdate{value: val, isSet: true}
}

func (v NullablePayoutsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


