/*
lomi. API

# lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
	"time"
)

// checks if the SpiQrCodesCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpiQrCodesCreate{}

// SpiQrCodesCreate Request body for creating a spi qr codes object. System-managed fields like `created_at`, `organization_id`, and IDs are automatically set.
type SpiQrCodesCreate struct {
	Categorie *string `json:"categorie,omitempty"`
	// Unique identifier (UUID format)
	CheckoutSessionId *string `json:"checkout_session_id,omitempty"`
	ComptePaye *string `json:"compte_paye,omitempty"`
	// ISO 8601 datetime
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Whether this resource is currently active
	IsActive *bool `json:"is_active,omitempty"`
	IsUsed *bool `json:"is_used,omitempty"`
	// Set of key-value pairs for storing additional information
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Montant *float64 `json:"montant,omitempty"`
	Name *string `json:"name,omitempty"`
	PayeurAlias *string `json:"payeur_alias,omitempty"`
	// Unique identifier (UUID format)
	PaymentRequestId *string `json:"payment_request_id,omitempty"`
	// Unique identifier (UUID format)
	PlanId *string `json:"plan_id,omitempty"`
	// Unique identifier (UUID format)
	ProductId *string `json:"product_id,omitempty"`
	QrCodeData *string `json:"qr_code_data,omitempty"`
	// Unique identifier (UUID format)
	QrCodeId *string `json:"qr_code_id,omitempty"`
	QrCodeImageData *string `json:"qr_code_image_data,omitempty"`
	// URL/URI
	QrCodeImageUrl *string `json:"qr_code_image_url,omitempty"`
	QrCodeType *string `json:"qr_code_type,omitempty"`
}

// NewSpiQrCodesCreate instantiates a new SpiQrCodesCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpiQrCodesCreate() *SpiQrCodesCreate {
	this := SpiQrCodesCreate{}
	return &this
}

// NewSpiQrCodesCreateWithDefaults instantiates a new SpiQrCodesCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpiQrCodesCreateWithDefaults() *SpiQrCodesCreate {
	this := SpiQrCodesCreate{}
	return &this
}

// GetCategorie returns the Categorie field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetCategorie() string {
	if o == nil || IsNil(o.Categorie) {
		var ret string
		return ret
	}
	return *o.Categorie
}

// GetCategorieOk returns a tuple with the Categorie field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetCategorieOk() (*string, bool) {
	if o == nil || IsNil(o.Categorie) {
		return nil, false
	}
	return o.Categorie, true
}

// HasCategorie returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasCategorie() bool {
	if o != nil && !IsNil(o.Categorie) {
		return true
	}

	return false
}

// SetCategorie gets a reference to the given string and assigns it to the Categorie field.
func (o *SpiQrCodesCreate) SetCategorie(v string) {
	o.Categorie = &v
}

// GetCheckoutSessionId returns the CheckoutSessionId field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetCheckoutSessionId() string {
	if o == nil || IsNil(o.CheckoutSessionId) {
		var ret string
		return ret
	}
	return *o.CheckoutSessionId
}

// GetCheckoutSessionIdOk returns a tuple with the CheckoutSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetCheckoutSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CheckoutSessionId) {
		return nil, false
	}
	return o.CheckoutSessionId, true
}

// HasCheckoutSessionId returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasCheckoutSessionId() bool {
	if o != nil && !IsNil(o.CheckoutSessionId) {
		return true
	}

	return false
}

// SetCheckoutSessionId gets a reference to the given string and assigns it to the CheckoutSessionId field.
func (o *SpiQrCodesCreate) SetCheckoutSessionId(v string) {
	o.CheckoutSessionId = &v
}

// GetComptePaye returns the ComptePaye field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetComptePaye() string {
	if o == nil || IsNil(o.ComptePaye) {
		var ret string
		return ret
	}
	return *o.ComptePaye
}

// GetComptePayeOk returns a tuple with the ComptePaye field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetComptePayeOk() (*string, bool) {
	if o == nil || IsNil(o.ComptePaye) {
		return nil, false
	}
	return o.ComptePaye, true
}

// HasComptePaye returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasComptePaye() bool {
	if o != nil && !IsNil(o.ComptePaye) {
		return true
	}

	return false
}

// SetComptePaye gets a reference to the given string and assigns it to the ComptePaye field.
func (o *SpiQrCodesCreate) SetComptePaye(v string) {
	o.ComptePaye = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *SpiQrCodesCreate) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *SpiQrCodesCreate) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetIsUsed returns the IsUsed field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetIsUsed() bool {
	if o == nil || IsNil(o.IsUsed) {
		var ret bool
		return ret
	}
	return *o.IsUsed
}

// GetIsUsedOk returns a tuple with the IsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetIsUsedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUsed) {
		return nil, false
	}
	return o.IsUsed, true
}

// HasIsUsed returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasIsUsed() bool {
	if o != nil && !IsNil(o.IsUsed) {
		return true
	}

	return false
}

// SetIsUsed gets a reference to the given bool and assigns it to the IsUsed field.
func (o *SpiQrCodesCreate) SetIsUsed(v bool) {
	o.IsUsed = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *SpiQrCodesCreate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetMontant returns the Montant field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetMontant() float64 {
	if o == nil || IsNil(o.Montant) {
		var ret float64
		return ret
	}
	return *o.Montant
}

// GetMontantOk returns a tuple with the Montant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetMontantOk() (*float64, bool) {
	if o == nil || IsNil(o.Montant) {
		return nil, false
	}
	return o.Montant, true
}

// HasMontant returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasMontant() bool {
	if o != nil && !IsNil(o.Montant) {
		return true
	}

	return false
}

// SetMontant gets a reference to the given float64 and assigns it to the Montant field.
func (o *SpiQrCodesCreate) SetMontant(v float64) {
	o.Montant = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SpiQrCodesCreate) SetName(v string) {
	o.Name = &v
}

// GetPayeurAlias returns the PayeurAlias field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetPayeurAlias() string {
	if o == nil || IsNil(o.PayeurAlias) {
		var ret string
		return ret
	}
	return *o.PayeurAlias
}

// GetPayeurAliasOk returns a tuple with the PayeurAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetPayeurAliasOk() (*string, bool) {
	if o == nil || IsNil(o.PayeurAlias) {
		return nil, false
	}
	return o.PayeurAlias, true
}

// HasPayeurAlias returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasPayeurAlias() bool {
	if o != nil && !IsNil(o.PayeurAlias) {
		return true
	}

	return false
}

// SetPayeurAlias gets a reference to the given string and assigns it to the PayeurAlias field.
func (o *SpiQrCodesCreate) SetPayeurAlias(v string) {
	o.PayeurAlias = &v
}

// GetPaymentRequestId returns the PaymentRequestId field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetPaymentRequestId() string {
	if o == nil || IsNil(o.PaymentRequestId) {
		var ret string
		return ret
	}
	return *o.PaymentRequestId
}

// GetPaymentRequestIdOk returns a tuple with the PaymentRequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetPaymentRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentRequestId) {
		return nil, false
	}
	return o.PaymentRequestId, true
}

// HasPaymentRequestId returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasPaymentRequestId() bool {
	if o != nil && !IsNil(o.PaymentRequestId) {
		return true
	}

	return false
}

// SetPaymentRequestId gets a reference to the given string and assigns it to the PaymentRequestId field.
func (o *SpiQrCodesCreate) SetPaymentRequestId(v string) {
	o.PaymentRequestId = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetPlanId() string {
	if o == nil || IsNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetPlanIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *SpiQrCodesCreate) SetPlanId(v string) {
	o.PlanId = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *SpiQrCodesCreate) SetProductId(v string) {
	o.ProductId = &v
}

// GetQrCodeData returns the QrCodeData field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetQrCodeData() string {
	if o == nil || IsNil(o.QrCodeData) {
		var ret string
		return ret
	}
	return *o.QrCodeData
}

// GetQrCodeDataOk returns a tuple with the QrCodeData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetQrCodeDataOk() (*string, bool) {
	if o == nil || IsNil(o.QrCodeData) {
		return nil, false
	}
	return o.QrCodeData, true
}

// HasQrCodeData returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasQrCodeData() bool {
	if o != nil && !IsNil(o.QrCodeData) {
		return true
	}

	return false
}

// SetQrCodeData gets a reference to the given string and assigns it to the QrCodeData field.
func (o *SpiQrCodesCreate) SetQrCodeData(v string) {
	o.QrCodeData = &v
}

// GetQrCodeId returns the QrCodeId field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetQrCodeId() string {
	if o == nil || IsNil(o.QrCodeId) {
		var ret string
		return ret
	}
	return *o.QrCodeId
}

// GetQrCodeIdOk returns a tuple with the QrCodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetQrCodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.QrCodeId) {
		return nil, false
	}
	return o.QrCodeId, true
}

// HasQrCodeId returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasQrCodeId() bool {
	if o != nil && !IsNil(o.QrCodeId) {
		return true
	}

	return false
}

// SetQrCodeId gets a reference to the given string and assigns it to the QrCodeId field.
func (o *SpiQrCodesCreate) SetQrCodeId(v string) {
	o.QrCodeId = &v
}

// GetQrCodeImageData returns the QrCodeImageData field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetQrCodeImageData() string {
	if o == nil || IsNil(o.QrCodeImageData) {
		var ret string
		return ret
	}
	return *o.QrCodeImageData
}

// GetQrCodeImageDataOk returns a tuple with the QrCodeImageData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetQrCodeImageDataOk() (*string, bool) {
	if o == nil || IsNil(o.QrCodeImageData) {
		return nil, false
	}
	return o.QrCodeImageData, true
}

// HasQrCodeImageData returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasQrCodeImageData() bool {
	if o != nil && !IsNil(o.QrCodeImageData) {
		return true
	}

	return false
}

// SetQrCodeImageData gets a reference to the given string and assigns it to the QrCodeImageData field.
func (o *SpiQrCodesCreate) SetQrCodeImageData(v string) {
	o.QrCodeImageData = &v
}

// GetQrCodeImageUrl returns the QrCodeImageUrl field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetQrCodeImageUrl() string {
	if o == nil || IsNil(o.QrCodeImageUrl) {
		var ret string
		return ret
	}
	return *o.QrCodeImageUrl
}

// GetQrCodeImageUrlOk returns a tuple with the QrCodeImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetQrCodeImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.QrCodeImageUrl) {
		return nil, false
	}
	return o.QrCodeImageUrl, true
}

// HasQrCodeImageUrl returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasQrCodeImageUrl() bool {
	if o != nil && !IsNil(o.QrCodeImageUrl) {
		return true
	}

	return false
}

// SetQrCodeImageUrl gets a reference to the given string and assigns it to the QrCodeImageUrl field.
func (o *SpiQrCodesCreate) SetQrCodeImageUrl(v string) {
	o.QrCodeImageUrl = &v
}

// GetQrCodeType returns the QrCodeType field value if set, zero value otherwise.
func (o *SpiQrCodesCreate) GetQrCodeType() string {
	if o == nil || IsNil(o.QrCodeType) {
		var ret string
		return ret
	}
	return *o.QrCodeType
}

// GetQrCodeTypeOk returns a tuple with the QrCodeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpiQrCodesCreate) GetQrCodeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.QrCodeType) {
		return nil, false
	}
	return o.QrCodeType, true
}

// HasQrCodeType returns a boolean if a field has been set.
func (o *SpiQrCodesCreate) HasQrCodeType() bool {
	if o != nil && !IsNil(o.QrCodeType) {
		return true
	}

	return false
}

// SetQrCodeType gets a reference to the given string and assigns it to the QrCodeType field.
func (o *SpiQrCodesCreate) SetQrCodeType(v string) {
	o.QrCodeType = &v
}

func (o SpiQrCodesCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpiQrCodesCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categorie) {
		toSerialize["categorie"] = o.Categorie
	}
	if !IsNil(o.CheckoutSessionId) {
		toSerialize["checkout_session_id"] = o.CheckoutSessionId
	}
	if !IsNil(o.ComptePaye) {
		toSerialize["compte_paye"] = o.ComptePaye
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.IsUsed) {
		toSerialize["is_used"] = o.IsUsed
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Montant) {
		toSerialize["montant"] = o.Montant
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PayeurAlias) {
		toSerialize["payeur_alias"] = o.PayeurAlias
	}
	if !IsNil(o.PaymentRequestId) {
		toSerialize["payment_request_id"] = o.PaymentRequestId
	}
	if !IsNil(o.PlanId) {
		toSerialize["plan_id"] = o.PlanId
	}
	if !IsNil(o.ProductId) {
		toSerialize["product_id"] = o.ProductId
	}
	if !IsNil(o.QrCodeData) {
		toSerialize["qr_code_data"] = o.QrCodeData
	}
	if !IsNil(o.QrCodeId) {
		toSerialize["qr_code_id"] = o.QrCodeId
	}
	if !IsNil(o.QrCodeImageData) {
		toSerialize["qr_code_image_data"] = o.QrCodeImageData
	}
	if !IsNil(o.QrCodeImageUrl) {
		toSerialize["qr_code_image_url"] = o.QrCodeImageUrl
	}
	if !IsNil(o.QrCodeType) {
		toSerialize["qr_code_type"] = o.QrCodeType
	}
	return toSerialize, nil
}

type NullableSpiQrCodesCreate struct {
	value *SpiQrCodesCreate
	isSet bool
}

func (v NullableSpiQrCodesCreate) Get() *SpiQrCodesCreate {
	return v.value
}

func (v *NullableSpiQrCodesCreate) Set(val *SpiQrCodesCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSpiQrCodesCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSpiQrCodesCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpiQrCodesCreate(val *SpiQrCodesCreate) *NullableSpiQrCodesCreate {
	return &NullableSpiQrCodesCreate{value: val, isSet: true}
}

func (v NullableSpiQrCodesCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpiQrCodesCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


