/*
lomi. API

Payment processing API for francophone West African businesses.

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
)

// checks if the EventsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsUpdate{}

// EventsUpdate Request body for updating a events object. Only include fields you want to modify.
type EventsUpdate struct {
	// Unique identifier (UUID format)
	CustomerId *string `json:"customer_id,omitempty"`
	EventData map[string]interface{} `json:"event_data,omitempty"`
	// Unique identifier (UUID format)
	EventId *string `json:"event_id,omitempty"`
	EventName *string `json:"event_name,omitempty"`
	// Set of key-value pairs for storing additional information
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Unique identifier (UUID format)
	ProductId *string `json:"product_id,omitempty"`
}

// NewEventsUpdate instantiates a new EventsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsUpdate() *EventsUpdate {
	this := EventsUpdate{}
	return &this
}

// NewEventsUpdateWithDefaults instantiates a new EventsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsUpdateWithDefaults() *EventsUpdate {
	this := EventsUpdate{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *EventsUpdate) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsUpdate) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *EventsUpdate) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *EventsUpdate) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *EventsUpdate) GetEventData() map[string]interface{} {
	if o == nil || IsNil(o.EventData) {
		var ret map[string]interface{}
		return ret
	}
	return o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsUpdate) GetEventDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.EventData) {
		return map[string]interface{}{}, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *EventsUpdate) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given map[string]interface{} and assigns it to the EventData field.
func (o *EventsUpdate) SetEventData(v map[string]interface{}) {
	o.EventData = v
}

// GetEventId returns the EventId field value if set, zero value otherwise.
func (o *EventsUpdate) GetEventId() string {
	if o == nil || IsNil(o.EventId) {
		var ret string
		return ret
	}
	return *o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsUpdate) GetEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.EventId) {
		return nil, false
	}
	return o.EventId, true
}

// HasEventId returns a boolean if a field has been set.
func (o *EventsUpdate) HasEventId() bool {
	if o != nil && !IsNil(o.EventId) {
		return true
	}

	return false
}

// SetEventId gets a reference to the given string and assigns it to the EventId field.
func (o *EventsUpdate) SetEventId(v string) {
	o.EventId = &v
}

// GetEventName returns the EventName field value if set, zero value otherwise.
func (o *EventsUpdate) GetEventName() string {
	if o == nil || IsNil(o.EventName) {
		var ret string
		return ret
	}
	return *o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsUpdate) GetEventNameOk() (*string, bool) {
	if o == nil || IsNil(o.EventName) {
		return nil, false
	}
	return o.EventName, true
}

// HasEventName returns a boolean if a field has been set.
func (o *EventsUpdate) HasEventName() bool {
	if o != nil && !IsNil(o.EventName) {
		return true
	}

	return false
}

// SetEventName gets a reference to the given string and assigns it to the EventName field.
func (o *EventsUpdate) SetEventName(v string) {
	o.EventName = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *EventsUpdate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsUpdate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *EventsUpdate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *EventsUpdate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *EventsUpdate) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsUpdate) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *EventsUpdate) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *EventsUpdate) SetProductId(v string) {
	o.ProductId = &v
}

func (o EventsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.EventData) {
		toSerialize["event_data"] = o.EventData
	}
	if !IsNil(o.EventId) {
		toSerialize["event_id"] = o.EventId
	}
	if !IsNil(o.EventName) {
		toSerialize["event_name"] = o.EventName
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.ProductId) {
		toSerialize["product_id"] = o.ProductId
	}
	return toSerialize, nil
}

type NullableEventsUpdate struct {
	value *EventsUpdate
	isSet bool
}

func (v NullableEventsUpdate) Get() *EventsUpdate {
	return v.value
}

func (v *NullableEventsUpdate) Set(val *EventsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsUpdate(val *EventsUpdate) *NullableEventsUpdate {
	return &NullableEventsUpdate{value: val, isSet: true}
}

func (v NullableEventsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


