/*
lomi. API

# lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
	"fmt"
)

// PricingModelEnum Enum: pricing_model_enum
type PricingModelEnum string

// List of pricing_model_enum
const (
	STANDARD PricingModelEnum = "standard"
	PAY_WHAT_YOU_WANT PricingModelEnum = "pay_what_you_want"
	TIERED PricingModelEnum = "tiered"
	VOLUME PricingModelEnum = "volume"
)

// All allowed values of PricingModelEnum enum
var AllowedPricingModelEnumEnumValues = []PricingModelEnum{
	"standard",
	"pay_what_you_want",
	"tiered",
	"volume",
}

func (v *PricingModelEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PricingModelEnum(value)
	for _, existing := range AllowedPricingModelEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PricingModelEnum", value)
}

// NewPricingModelEnumFromValue returns a pointer to a valid PricingModelEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPricingModelEnumFromValue(v string) (*PricingModelEnum, error) {
	ev := PricingModelEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PricingModelEnum: valid values are %v", v, AllowedPricingModelEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PricingModelEnum) IsValid() bool {
	for _, existing := range AllowedPricingModelEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to pricing_model_enum value
func (v PricingModelEnum) Ptr() *PricingModelEnum {
	return &v
}

type NullablePricingModelEnum struct {
	value *PricingModelEnum
	isSet bool
}

func (v NullablePricingModelEnum) Get() *PricingModelEnum {
	return v.value
}

func (v *NullablePricingModelEnum) Set(val *PricingModelEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePricingModelEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePricingModelEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricingModelEnum(val *PricingModelEnum) *NullablePricingModelEnum {
	return &NullablePricingModelEnum{value: val, isSet: true}
}

func (v NullablePricingModelEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricingModelEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

