/*
lomi. API

Payment processing API for francophone West African businesses.

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
	"time"
)

// checks if the WebhooksCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhooksCreate{}

// WebhooksCreate Request body for creating a webhooks object. System-managed fields like `created_at`, `organization_id`, and IDs are automatically set.
type WebhooksCreate struct {
	AuthorizedEvents *string `json:"authorized_events,omitempty"`
	// Whether this resource is currently active
	IsActive *bool `json:"is_active,omitempty"`
	LastPayload map[string]interface{} `json:"last_payload,omitempty"`
	LastResponseBody *string `json:"last_response_body,omitempty"`
	LastResponseStatus *float64 `json:"last_response_status,omitempty"`
	// ISO 8601 datetime
	LastTriggeredAt *time.Time `json:"last_triggered_at,omitempty"`
	// Set of key-value pairs for storing additional information
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	RetryCount *float64 `json:"retry_count,omitempty"`
	SpiEventTypes *string `json:"spi_event_types,omitempty"`
	SupportsSpi *bool `json:"supports_spi,omitempty"`
	// URL/URI
	Url *string `json:"url,omitempty"`
	VerificationToken *string `json:"verification_token,omitempty"`
	// Unique identifier (UUID format)
	WebhookId *string `json:"webhook_id,omitempty"`
}

// NewWebhooksCreate instantiates a new WebhooksCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksCreate() *WebhooksCreate {
	this := WebhooksCreate{}
	return &this
}

// NewWebhooksCreateWithDefaults instantiates a new WebhooksCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksCreateWithDefaults() *WebhooksCreate {
	this := WebhooksCreate{}
	return &this
}

// GetAuthorizedEvents returns the AuthorizedEvents field value if set, zero value otherwise.
func (o *WebhooksCreate) GetAuthorizedEvents() string {
	if o == nil || IsNil(o.AuthorizedEvents) {
		var ret string
		return ret
	}
	return *o.AuthorizedEvents
}

// GetAuthorizedEventsOk returns a tuple with the AuthorizedEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetAuthorizedEventsOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizedEvents) {
		return nil, false
	}
	return o.AuthorizedEvents, true
}

// HasAuthorizedEvents returns a boolean if a field has been set.
func (o *WebhooksCreate) HasAuthorizedEvents() bool {
	if o != nil && !IsNil(o.AuthorizedEvents) {
		return true
	}

	return false
}

// SetAuthorizedEvents gets a reference to the given string and assigns it to the AuthorizedEvents field.
func (o *WebhooksCreate) SetAuthorizedEvents(v string) {
	o.AuthorizedEvents = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *WebhooksCreate) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *WebhooksCreate) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *WebhooksCreate) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetLastPayload returns the LastPayload field value if set, zero value otherwise.
func (o *WebhooksCreate) GetLastPayload() map[string]interface{} {
	if o == nil || IsNil(o.LastPayload) {
		var ret map[string]interface{}
		return ret
	}
	return o.LastPayload
}

// GetLastPayloadOk returns a tuple with the LastPayload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetLastPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.LastPayload) {
		return map[string]interface{}{}, false
	}
	return o.LastPayload, true
}

// HasLastPayload returns a boolean if a field has been set.
func (o *WebhooksCreate) HasLastPayload() bool {
	if o != nil && !IsNil(o.LastPayload) {
		return true
	}

	return false
}

// SetLastPayload gets a reference to the given map[string]interface{} and assigns it to the LastPayload field.
func (o *WebhooksCreate) SetLastPayload(v map[string]interface{}) {
	o.LastPayload = v
}

// GetLastResponseBody returns the LastResponseBody field value if set, zero value otherwise.
func (o *WebhooksCreate) GetLastResponseBody() string {
	if o == nil || IsNil(o.LastResponseBody) {
		var ret string
		return ret
	}
	return *o.LastResponseBody
}

// GetLastResponseBodyOk returns a tuple with the LastResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetLastResponseBodyOk() (*string, bool) {
	if o == nil || IsNil(o.LastResponseBody) {
		return nil, false
	}
	return o.LastResponseBody, true
}

// HasLastResponseBody returns a boolean if a field has been set.
func (o *WebhooksCreate) HasLastResponseBody() bool {
	if o != nil && !IsNil(o.LastResponseBody) {
		return true
	}

	return false
}

// SetLastResponseBody gets a reference to the given string and assigns it to the LastResponseBody field.
func (o *WebhooksCreate) SetLastResponseBody(v string) {
	o.LastResponseBody = &v
}

// GetLastResponseStatus returns the LastResponseStatus field value if set, zero value otherwise.
func (o *WebhooksCreate) GetLastResponseStatus() float64 {
	if o == nil || IsNil(o.LastResponseStatus) {
		var ret float64
		return ret
	}
	return *o.LastResponseStatus
}

// GetLastResponseStatusOk returns a tuple with the LastResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetLastResponseStatusOk() (*float64, bool) {
	if o == nil || IsNil(o.LastResponseStatus) {
		return nil, false
	}
	return o.LastResponseStatus, true
}

// HasLastResponseStatus returns a boolean if a field has been set.
func (o *WebhooksCreate) HasLastResponseStatus() bool {
	if o != nil && !IsNil(o.LastResponseStatus) {
		return true
	}

	return false
}

// SetLastResponseStatus gets a reference to the given float64 and assigns it to the LastResponseStatus field.
func (o *WebhooksCreate) SetLastResponseStatus(v float64) {
	o.LastResponseStatus = &v
}

// GetLastTriggeredAt returns the LastTriggeredAt field value if set, zero value otherwise.
func (o *WebhooksCreate) GetLastTriggeredAt() time.Time {
	if o == nil || IsNil(o.LastTriggeredAt) {
		var ret time.Time
		return ret
	}
	return *o.LastTriggeredAt
}

// GetLastTriggeredAtOk returns a tuple with the LastTriggeredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetLastTriggeredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastTriggeredAt) {
		return nil, false
	}
	return o.LastTriggeredAt, true
}

// HasLastTriggeredAt returns a boolean if a field has been set.
func (o *WebhooksCreate) HasLastTriggeredAt() bool {
	if o != nil && !IsNil(o.LastTriggeredAt) {
		return true
	}

	return false
}

// SetLastTriggeredAt gets a reference to the given time.Time and assigns it to the LastTriggeredAt field.
func (o *WebhooksCreate) SetLastTriggeredAt(v time.Time) {
	o.LastTriggeredAt = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *WebhooksCreate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *WebhooksCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *WebhooksCreate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetRetryCount returns the RetryCount field value if set, zero value otherwise.
func (o *WebhooksCreate) GetRetryCount() float64 {
	if o == nil || IsNil(o.RetryCount) {
		var ret float64
		return ret
	}
	return *o.RetryCount
}

// GetRetryCountOk returns a tuple with the RetryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetRetryCountOk() (*float64, bool) {
	if o == nil || IsNil(o.RetryCount) {
		return nil, false
	}
	return o.RetryCount, true
}

// HasRetryCount returns a boolean if a field has been set.
func (o *WebhooksCreate) HasRetryCount() bool {
	if o != nil && !IsNil(o.RetryCount) {
		return true
	}

	return false
}

// SetRetryCount gets a reference to the given float64 and assigns it to the RetryCount field.
func (o *WebhooksCreate) SetRetryCount(v float64) {
	o.RetryCount = &v
}

// GetSpiEventTypes returns the SpiEventTypes field value if set, zero value otherwise.
func (o *WebhooksCreate) GetSpiEventTypes() string {
	if o == nil || IsNil(o.SpiEventTypes) {
		var ret string
		return ret
	}
	return *o.SpiEventTypes
}

// GetSpiEventTypesOk returns a tuple with the SpiEventTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetSpiEventTypesOk() (*string, bool) {
	if o == nil || IsNil(o.SpiEventTypes) {
		return nil, false
	}
	return o.SpiEventTypes, true
}

// HasSpiEventTypes returns a boolean if a field has been set.
func (o *WebhooksCreate) HasSpiEventTypes() bool {
	if o != nil && !IsNil(o.SpiEventTypes) {
		return true
	}

	return false
}

// SetSpiEventTypes gets a reference to the given string and assigns it to the SpiEventTypes field.
func (o *WebhooksCreate) SetSpiEventTypes(v string) {
	o.SpiEventTypes = &v
}

// GetSupportsSpi returns the SupportsSpi field value if set, zero value otherwise.
func (o *WebhooksCreate) GetSupportsSpi() bool {
	if o == nil || IsNil(o.SupportsSpi) {
		var ret bool
		return ret
	}
	return *o.SupportsSpi
}

// GetSupportsSpiOk returns a tuple with the SupportsSpi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetSupportsSpiOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportsSpi) {
		return nil, false
	}
	return o.SupportsSpi, true
}

// HasSupportsSpi returns a boolean if a field has been set.
func (o *WebhooksCreate) HasSupportsSpi() bool {
	if o != nil && !IsNil(o.SupportsSpi) {
		return true
	}

	return false
}

// SetSupportsSpi gets a reference to the given bool and assigns it to the SupportsSpi field.
func (o *WebhooksCreate) SetSupportsSpi(v bool) {
	o.SupportsSpi = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebhooksCreate) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebhooksCreate) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebhooksCreate) SetUrl(v string) {
	o.Url = &v
}

// GetVerificationToken returns the VerificationToken field value if set, zero value otherwise.
func (o *WebhooksCreate) GetVerificationToken() string {
	if o == nil || IsNil(o.VerificationToken) {
		var ret string
		return ret
	}
	return *o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetVerificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.VerificationToken) {
		return nil, false
	}
	return o.VerificationToken, true
}

// HasVerificationToken returns a boolean if a field has been set.
func (o *WebhooksCreate) HasVerificationToken() bool {
	if o != nil && !IsNil(o.VerificationToken) {
		return true
	}

	return false
}

// SetVerificationToken gets a reference to the given string and assigns it to the VerificationToken field.
func (o *WebhooksCreate) SetVerificationToken(v string) {
	o.VerificationToken = &v
}

// GetWebhookId returns the WebhookId field value if set, zero value otherwise.
func (o *WebhooksCreate) GetWebhookId() string {
	if o == nil || IsNil(o.WebhookId) {
		var ret string
		return ret
	}
	return *o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksCreate) GetWebhookIdOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookId) {
		return nil, false
	}
	return o.WebhookId, true
}

// HasWebhookId returns a boolean if a field has been set.
func (o *WebhooksCreate) HasWebhookId() bool {
	if o != nil && !IsNil(o.WebhookId) {
		return true
	}

	return false
}

// SetWebhookId gets a reference to the given string and assigns it to the WebhookId field.
func (o *WebhooksCreate) SetWebhookId(v string) {
	o.WebhookId = &v
}

func (o WebhooksCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhooksCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorizedEvents) {
		toSerialize["authorized_events"] = o.AuthorizedEvents
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.LastPayload) {
		toSerialize["last_payload"] = o.LastPayload
	}
	if !IsNil(o.LastResponseBody) {
		toSerialize["last_response_body"] = o.LastResponseBody
	}
	if !IsNil(o.LastResponseStatus) {
		toSerialize["last_response_status"] = o.LastResponseStatus
	}
	if !IsNil(o.LastTriggeredAt) {
		toSerialize["last_triggered_at"] = o.LastTriggeredAt
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.RetryCount) {
		toSerialize["retry_count"] = o.RetryCount
	}
	if !IsNil(o.SpiEventTypes) {
		toSerialize["spi_event_types"] = o.SpiEventTypes
	}
	if !IsNil(o.SupportsSpi) {
		toSerialize["supports_spi"] = o.SupportsSpi
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.VerificationToken) {
		toSerialize["verification_token"] = o.VerificationToken
	}
	if !IsNil(o.WebhookId) {
		toSerialize["webhook_id"] = o.WebhookId
	}
	return toSerialize, nil
}

type NullableWebhooksCreate struct {
	value *WebhooksCreate
	isSet bool
}

func (v NullableWebhooksCreate) Get() *WebhooksCreate {
	return v.value
}

func (v *NullableWebhooksCreate) Set(val *WebhooksCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksCreate(val *WebhooksCreate) *NullableWebhooksCreate {
	return &NullableWebhooksCreate{value: val, isSet: true}
}

func (v NullableWebhooksCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhooksCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


