/*
lomi. API

# lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
	"time"
)

// checks if the Customers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Customers{}

// Customers customers resource object
type Customers struct {
	Address *string `json:"address,omitempty"`
	City *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
	// ISO 8601 datetime
	CreatedAt *time.Time `json:"created_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	// Unique identifier (UUID format)
	CustomerId *string `json:"customer_id,omitempty"`
	// ISO 8601 datetime
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Email address
	Email *string `json:"email,omitempty"`
	Environment *string `json:"environment,omitempty"`
	IsBusiness *bool `json:"is_business,omitempty"`
	// Soft deletion flag
	IsDeleted *bool `json:"is_deleted,omitempty"`
	// Set of key-value pairs for storing additional information
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Name *string `json:"name,omitempty"`
	// Unique identifier (UUID format)
	OrganizationId *string `json:"organization_id,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	PostalCode *string `json:"postal_code,omitempty"`
	SpiAliasMbno *string `json:"spi_alias_mbno,omitempty"`
	SpiAliasShid *string `json:"spi_alias_shid,omitempty"`
	SpiPrimaryAlias *string `json:"spi_primary_alias,omitempty"`
	// ISO 8601 datetime
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	WhatsappNumber *string `json:"whatsapp_number,omitempty"`
}

// NewCustomers instantiates a new Customers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomers() *Customers {
	this := Customers{}
	return &this
}

// NewCustomersWithDefaults instantiates a new Customers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomersWithDefaults() *Customers {
	this := Customers{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Customers) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Customers) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *Customers) SetAddress(v string) {
	o.Address = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *Customers) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *Customers) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *Customers) SetCity(v string) {
	o.City = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *Customers) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *Customers) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *Customers) SetCountry(v string) {
	o.Country = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Customers) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Customers) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Customers) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *Customers) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *Customers) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *Customers) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *Customers) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *Customers) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *Customers) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *Customers) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Customers) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *Customers) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Customers) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Customers) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Customers) SetEmail(v string) {
	o.Email = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *Customers) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *Customers) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *Customers) SetEnvironment(v string) {
	o.Environment = &v
}

// GetIsBusiness returns the IsBusiness field value if set, zero value otherwise.
func (o *Customers) GetIsBusiness() bool {
	if o == nil || IsNil(o.IsBusiness) {
		var ret bool
		return ret
	}
	return *o.IsBusiness
}

// GetIsBusinessOk returns a tuple with the IsBusiness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetIsBusinessOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBusiness) {
		return nil, false
	}
	return o.IsBusiness, true
}

// HasIsBusiness returns a boolean if a field has been set.
func (o *Customers) HasIsBusiness() bool {
	if o != nil && !IsNil(o.IsBusiness) {
		return true
	}

	return false
}

// SetIsBusiness gets a reference to the given bool and assigns it to the IsBusiness field.
func (o *Customers) SetIsBusiness(v bool) {
	o.IsBusiness = &v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *Customers) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *Customers) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *Customers) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Customers) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Customers) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Customers) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Customers) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Customers) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Customers) SetName(v string) {
	o.Name = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *Customers) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *Customers) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *Customers) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *Customers) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *Customers) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *Customers) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *Customers) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *Customers) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *Customers) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetSpiAliasMbno returns the SpiAliasMbno field value if set, zero value otherwise.
func (o *Customers) GetSpiAliasMbno() string {
	if o == nil || IsNil(o.SpiAliasMbno) {
		var ret string
		return ret
	}
	return *o.SpiAliasMbno
}

// GetSpiAliasMbnoOk returns a tuple with the SpiAliasMbno field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetSpiAliasMbnoOk() (*string, bool) {
	if o == nil || IsNil(o.SpiAliasMbno) {
		return nil, false
	}
	return o.SpiAliasMbno, true
}

// HasSpiAliasMbno returns a boolean if a field has been set.
func (o *Customers) HasSpiAliasMbno() bool {
	if o != nil && !IsNil(o.SpiAliasMbno) {
		return true
	}

	return false
}

// SetSpiAliasMbno gets a reference to the given string and assigns it to the SpiAliasMbno field.
func (o *Customers) SetSpiAliasMbno(v string) {
	o.SpiAliasMbno = &v
}

// GetSpiAliasShid returns the SpiAliasShid field value if set, zero value otherwise.
func (o *Customers) GetSpiAliasShid() string {
	if o == nil || IsNil(o.SpiAliasShid) {
		var ret string
		return ret
	}
	return *o.SpiAliasShid
}

// GetSpiAliasShidOk returns a tuple with the SpiAliasShid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetSpiAliasShidOk() (*string, bool) {
	if o == nil || IsNil(o.SpiAliasShid) {
		return nil, false
	}
	return o.SpiAliasShid, true
}

// HasSpiAliasShid returns a boolean if a field has been set.
func (o *Customers) HasSpiAliasShid() bool {
	if o != nil && !IsNil(o.SpiAliasShid) {
		return true
	}

	return false
}

// SetSpiAliasShid gets a reference to the given string and assigns it to the SpiAliasShid field.
func (o *Customers) SetSpiAliasShid(v string) {
	o.SpiAliasShid = &v
}

// GetSpiPrimaryAlias returns the SpiPrimaryAlias field value if set, zero value otherwise.
func (o *Customers) GetSpiPrimaryAlias() string {
	if o == nil || IsNil(o.SpiPrimaryAlias) {
		var ret string
		return ret
	}
	return *o.SpiPrimaryAlias
}

// GetSpiPrimaryAliasOk returns a tuple with the SpiPrimaryAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetSpiPrimaryAliasOk() (*string, bool) {
	if o == nil || IsNil(o.SpiPrimaryAlias) {
		return nil, false
	}
	return o.SpiPrimaryAlias, true
}

// HasSpiPrimaryAlias returns a boolean if a field has been set.
func (o *Customers) HasSpiPrimaryAlias() bool {
	if o != nil && !IsNil(o.SpiPrimaryAlias) {
		return true
	}

	return false
}

// SetSpiPrimaryAlias gets a reference to the given string and assigns it to the SpiPrimaryAlias field.
func (o *Customers) SetSpiPrimaryAlias(v string) {
	o.SpiPrimaryAlias = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Customers) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Customers) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Customers) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetWhatsappNumber returns the WhatsappNumber field value if set, zero value otherwise.
func (o *Customers) GetWhatsappNumber() string {
	if o == nil || IsNil(o.WhatsappNumber) {
		var ret string
		return ret
	}
	return *o.WhatsappNumber
}

// GetWhatsappNumberOk returns a tuple with the WhatsappNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Customers) GetWhatsappNumberOk() (*string, bool) {
	if o == nil || IsNil(o.WhatsappNumber) {
		return nil, false
	}
	return o.WhatsappNumber, true
}

// HasWhatsappNumber returns a boolean if a field has been set.
func (o *Customers) HasWhatsappNumber() bool {
	if o != nil && !IsNil(o.WhatsappNumber) {
		return true
	}

	return false
}

// SetWhatsappNumber gets a reference to the given string and assigns it to the WhatsappNumber field.
func (o *Customers) SetWhatsappNumber(v string) {
	o.WhatsappNumber = &v
}

func (o Customers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Customers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.IsBusiness) {
		toSerialize["is_business"] = o.IsBusiness
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postal_code"] = o.PostalCode
	}
	if !IsNil(o.SpiAliasMbno) {
		toSerialize["spi_alias_mbno"] = o.SpiAliasMbno
	}
	if !IsNil(o.SpiAliasShid) {
		toSerialize["spi_alias_shid"] = o.SpiAliasShid
	}
	if !IsNil(o.SpiPrimaryAlias) {
		toSerialize["spi_primary_alias"] = o.SpiPrimaryAlias
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.WhatsappNumber) {
		toSerialize["whatsapp_number"] = o.WhatsappNumber
	}
	return toSerialize, nil
}

type NullableCustomers struct {
	value *Customers
	isSet bool
}

func (v NullableCustomers) Get() *Customers {
	return v.value
}

func (v *NullableCustomers) Set(val *Customers) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomers) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomers(val *Customers) *NullableCustomers {
	return &NullableCustomers{value: val, isSet: true}
}

func (v NullableCustomers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


