/*
lomi. API

# lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

API version: 1.1.0
Contact: hello@lomi.africa
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lomisdk

import (
	"encoding/json"
	"time"
)

// checks if the WebhookDeliveryLogsCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveryLogsCreate{}

// WebhookDeliveryLogsCreate Create webhook_delivery_logs input
type WebhookDeliveryLogsCreate struct {
	AttemptNumber *float64 `json:"attempt_number,omitempty"`
	ComptePaye *string `json:"compte_paye,omitempty"`
	ComptePayeur *string `json:"compte_payeur,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	EventType *string `json:"event_type,omitempty"`
	Headers map[string]interface{} `json:"headers,omitempty"`
	IpAddress *string `json:"ip_address,omitempty"`
	LogId *string `json:"log_id,omitempty"`
	Montant *float64 `json:"montant,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	RequestDurationMs *float64 `json:"request_duration_ms,omitempty"`
	ResponseBody *string `json:"response_body,omitempty"`
	ResponseStatus *float64 `json:"response_status,omitempty"`
	SpiEventCode *string `json:"spi_event_code,omitempty"`
	SpiTxId *string `json:"spi_tx_id,omitempty"`
	Success *bool `json:"success,omitempty"`
	UserAgent *string `json:"user_agent,omitempty"`
	WebhookId *string `json:"webhook_id,omitempty"`
}

// NewWebhookDeliveryLogsCreate instantiates a new WebhookDeliveryLogsCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryLogsCreate() *WebhookDeliveryLogsCreate {
	this := WebhookDeliveryLogsCreate{}
	return &this
}

// NewWebhookDeliveryLogsCreateWithDefaults instantiates a new WebhookDeliveryLogsCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryLogsCreateWithDefaults() *WebhookDeliveryLogsCreate {
	this := WebhookDeliveryLogsCreate{}
	return &this
}

// GetAttemptNumber returns the AttemptNumber field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetAttemptNumber() float64 {
	if o == nil || IsNil(o.AttemptNumber) {
		var ret float64
		return ret
	}
	return *o.AttemptNumber
}

// GetAttemptNumberOk returns a tuple with the AttemptNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetAttemptNumberOk() (*float64, bool) {
	if o == nil || IsNil(o.AttemptNumber) {
		return nil, false
	}
	return o.AttemptNumber, true
}

// HasAttemptNumber returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasAttemptNumber() bool {
	if o != nil && !IsNil(o.AttemptNumber) {
		return true
	}

	return false
}

// SetAttemptNumber gets a reference to the given float64 and assigns it to the AttemptNumber field.
func (o *WebhookDeliveryLogsCreate) SetAttemptNumber(v float64) {
	o.AttemptNumber = &v
}

// GetComptePaye returns the ComptePaye field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetComptePaye() string {
	if o == nil || IsNil(o.ComptePaye) {
		var ret string
		return ret
	}
	return *o.ComptePaye
}

// GetComptePayeOk returns a tuple with the ComptePaye field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetComptePayeOk() (*string, bool) {
	if o == nil || IsNil(o.ComptePaye) {
		return nil, false
	}
	return o.ComptePaye, true
}

// HasComptePaye returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasComptePaye() bool {
	if o != nil && !IsNil(o.ComptePaye) {
		return true
	}

	return false
}

// SetComptePaye gets a reference to the given string and assigns it to the ComptePaye field.
func (o *WebhookDeliveryLogsCreate) SetComptePaye(v string) {
	o.ComptePaye = &v
}

// GetComptePayeur returns the ComptePayeur field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetComptePayeur() string {
	if o == nil || IsNil(o.ComptePayeur) {
		var ret string
		return ret
	}
	return *o.ComptePayeur
}

// GetComptePayeurOk returns a tuple with the ComptePayeur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetComptePayeurOk() (*string, bool) {
	if o == nil || IsNil(o.ComptePayeur) {
		return nil, false
	}
	return o.ComptePayeur, true
}

// HasComptePayeur returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasComptePayeur() bool {
	if o != nil && !IsNil(o.ComptePayeur) {
		return true
	}

	return false
}

// SetComptePayeur gets a reference to the given string and assigns it to the ComptePayeur field.
func (o *WebhookDeliveryLogsCreate) SetComptePayeur(v string) {
	o.ComptePayeur = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WebhookDeliveryLogsCreate) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebhookDeliveryLogsCreate) SetEventType(v string) {
	o.EventType = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetHeaders() map[string]interface{} {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]interface{}{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]interface{} and assigns it to the Headers field.
func (o *WebhookDeliveryLogsCreate) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *WebhookDeliveryLogsCreate) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetLogId returns the LogId field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetLogId() string {
	if o == nil || IsNil(o.LogId) {
		var ret string
		return ret
	}
	return *o.LogId
}

// GetLogIdOk returns a tuple with the LogId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetLogIdOk() (*string, bool) {
	if o == nil || IsNil(o.LogId) {
		return nil, false
	}
	return o.LogId, true
}

// HasLogId returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasLogId() bool {
	if o != nil && !IsNil(o.LogId) {
		return true
	}

	return false
}

// SetLogId gets a reference to the given string and assigns it to the LogId field.
func (o *WebhookDeliveryLogsCreate) SetLogId(v string) {
	o.LogId = &v
}

// GetMontant returns the Montant field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetMontant() float64 {
	if o == nil || IsNil(o.Montant) {
		var ret float64
		return ret
	}
	return *o.Montant
}

// GetMontantOk returns a tuple with the Montant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetMontantOk() (*float64, bool) {
	if o == nil || IsNil(o.Montant) {
		return nil, false
	}
	return o.Montant, true
}

// HasMontant returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasMontant() bool {
	if o != nil && !IsNil(o.Montant) {
		return true
	}

	return false
}

// SetMontant gets a reference to the given float64 and assigns it to the Montant field.
func (o *WebhookDeliveryLogsCreate) SetMontant(v float64) {
	o.Montant = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *WebhookDeliveryLogsCreate) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *WebhookDeliveryLogsCreate) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetRequestDurationMs returns the RequestDurationMs field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetRequestDurationMs() float64 {
	if o == nil || IsNil(o.RequestDurationMs) {
		var ret float64
		return ret
	}
	return *o.RequestDurationMs
}

// GetRequestDurationMsOk returns a tuple with the RequestDurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetRequestDurationMsOk() (*float64, bool) {
	if o == nil || IsNil(o.RequestDurationMs) {
		return nil, false
	}
	return o.RequestDurationMs, true
}

// HasRequestDurationMs returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasRequestDurationMs() bool {
	if o != nil && !IsNil(o.RequestDurationMs) {
		return true
	}

	return false
}

// SetRequestDurationMs gets a reference to the given float64 and assigns it to the RequestDurationMs field.
func (o *WebhookDeliveryLogsCreate) SetRequestDurationMs(v float64) {
	o.RequestDurationMs = &v
}

// GetResponseBody returns the ResponseBody field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetResponseBody() string {
	if o == nil || IsNil(o.ResponseBody) {
		var ret string
		return ret
	}
	return *o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetResponseBodyOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseBody) {
		return nil, false
	}
	return o.ResponseBody, true
}

// HasResponseBody returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasResponseBody() bool {
	if o != nil && !IsNil(o.ResponseBody) {
		return true
	}

	return false
}

// SetResponseBody gets a reference to the given string and assigns it to the ResponseBody field.
func (o *WebhookDeliveryLogsCreate) SetResponseBody(v string) {
	o.ResponseBody = &v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetResponseStatus() float64 {
	if o == nil || IsNil(o.ResponseStatus) {
		var ret float64
		return ret
	}
	return *o.ResponseStatus
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetResponseStatusOk() (*float64, bool) {
	if o == nil || IsNil(o.ResponseStatus) {
		return nil, false
	}
	return o.ResponseStatus, true
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasResponseStatus() bool {
	if o != nil && !IsNil(o.ResponseStatus) {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given float64 and assigns it to the ResponseStatus field.
func (o *WebhookDeliveryLogsCreate) SetResponseStatus(v float64) {
	o.ResponseStatus = &v
}

// GetSpiEventCode returns the SpiEventCode field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetSpiEventCode() string {
	if o == nil || IsNil(o.SpiEventCode) {
		var ret string
		return ret
	}
	return *o.SpiEventCode
}

// GetSpiEventCodeOk returns a tuple with the SpiEventCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetSpiEventCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SpiEventCode) {
		return nil, false
	}
	return o.SpiEventCode, true
}

// HasSpiEventCode returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasSpiEventCode() bool {
	if o != nil && !IsNil(o.SpiEventCode) {
		return true
	}

	return false
}

// SetSpiEventCode gets a reference to the given string and assigns it to the SpiEventCode field.
func (o *WebhookDeliveryLogsCreate) SetSpiEventCode(v string) {
	o.SpiEventCode = &v
}

// GetSpiTxId returns the SpiTxId field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetSpiTxId() string {
	if o == nil || IsNil(o.SpiTxId) {
		var ret string
		return ret
	}
	return *o.SpiTxId
}

// GetSpiTxIdOk returns a tuple with the SpiTxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetSpiTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpiTxId) {
		return nil, false
	}
	return o.SpiTxId, true
}

// HasSpiTxId returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasSpiTxId() bool {
	if o != nil && !IsNil(o.SpiTxId) {
		return true
	}

	return false
}

// SetSpiTxId gets a reference to the given string and assigns it to the SpiTxId field.
func (o *WebhookDeliveryLogsCreate) SetSpiTxId(v string) {
	o.SpiTxId = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *WebhookDeliveryLogsCreate) SetSuccess(v bool) {
	o.Success = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetUserAgent() string {
	if o == nil || IsNil(o.UserAgent) {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetUserAgentOk() (*string, bool) {
	if o == nil || IsNil(o.UserAgent) {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasUserAgent() bool {
	if o != nil && !IsNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *WebhookDeliveryLogsCreate) SetUserAgent(v string) {
	o.UserAgent = &v
}

// GetWebhookId returns the WebhookId field value if set, zero value otherwise.
func (o *WebhookDeliveryLogsCreate) GetWebhookId() string {
	if o == nil || IsNil(o.WebhookId) {
		var ret string
		return ret
	}
	return *o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryLogsCreate) GetWebhookIdOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookId) {
		return nil, false
	}
	return o.WebhookId, true
}

// HasWebhookId returns a boolean if a field has been set.
func (o *WebhookDeliveryLogsCreate) HasWebhookId() bool {
	if o != nil && !IsNil(o.WebhookId) {
		return true
	}

	return false
}

// SetWebhookId gets a reference to the given string and assigns it to the WebhookId field.
func (o *WebhookDeliveryLogsCreate) SetWebhookId(v string) {
	o.WebhookId = &v
}

func (o WebhookDeliveryLogsCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveryLogsCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttemptNumber) {
		toSerialize["attempt_number"] = o.AttemptNumber
	}
	if !IsNil(o.ComptePaye) {
		toSerialize["compte_paye"] = o.ComptePaye
	}
	if !IsNil(o.ComptePayeur) {
		toSerialize["compte_payeur"] = o.ComptePayeur
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ip_address"] = o.IpAddress
	}
	if !IsNil(o.LogId) {
		toSerialize["log_id"] = o.LogId
	}
	if !IsNil(o.Montant) {
		toSerialize["montant"] = o.Montant
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.RequestDurationMs) {
		toSerialize["request_duration_ms"] = o.RequestDurationMs
	}
	if !IsNil(o.ResponseBody) {
		toSerialize["response_body"] = o.ResponseBody
	}
	if !IsNil(o.ResponseStatus) {
		toSerialize["response_status"] = o.ResponseStatus
	}
	if !IsNil(o.SpiEventCode) {
		toSerialize["spi_event_code"] = o.SpiEventCode
	}
	if !IsNil(o.SpiTxId) {
		toSerialize["spi_tx_id"] = o.SpiTxId
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.UserAgent) {
		toSerialize["user_agent"] = o.UserAgent
	}
	if !IsNil(o.WebhookId) {
		toSerialize["webhook_id"] = o.WebhookId
	}
	return toSerialize, nil
}

type NullableWebhookDeliveryLogsCreate struct {
	value *WebhookDeliveryLogsCreate
	isSet bool
}

func (v NullableWebhookDeliveryLogsCreate) Get() *WebhookDeliveryLogsCreate {
	return v.value
}

func (v *NullableWebhookDeliveryLogsCreate) Set(val *WebhookDeliveryLogsCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryLogsCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryLogsCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryLogsCreate(val *WebhookDeliveryLogsCreate) *NullableWebhookDeliveryLogsCreate {
	return &NullableWebhookDeliveryLogsCreate{value: val, isSet: true}
}

func (v NullableWebhookDeliveryLogsCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryLogsCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


