# coding: utf-8

"""
    lomi. API

    Payment processing API for francophone West African businesses.

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_list_transactions(self) -> None:
        """Test case for list_transactions

        List transactions
        """
        pass

    def test_retrieve_transaction(self) -> None:
        """Test case for retrieve_transaction

        Retrieve transaction
        """
        pass


if __name__ == '__main__':
    unittest.main()
