# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.models.products_get200_response import ProductsGet200Response

class TestProductsGet200Response(unittest.TestCase):
    """ProductsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductsGet200Response:
        """Test ProductsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductsGet200Response`
        """
        model = ProductsGet200Response()
        if include_optional:
            return ProductsGet200Response(
                data = [
                    lomi_sdk.models.products.products(
                        billing_frequency = '', 
                        charge_day = 1.337, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        description = '', 
                        display_on_storefront = True, 
                        environment = '', 
                        failed_payment_action = '', 
                        first_payment_type = '', 
                        image_url = '', 
                        is_active = True, 
                        metadata = lomi_sdk.models.metadata.metadata(), 
                        name = '', 
                        organization_id = '', 
                        product_id = '', 
                        product_type = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        usage_aggregation = '', 
                        usage_unit = '', )
                    ],
                pagination = lomi_sdk.models._customers_get_200_response_pagination._customers_get_200_response_pagination(
                    limit = 56, 
                    offset = 56, 
                    total = 56, )
            )
        else:
            return ProductsGet200Response(
        )
        """

    def testProductsGet200Response(self):
        """Test ProductsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
