# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.models.list_events200_response import ListEvents200Response

class TestListEvents200Response(unittest.TestCase):
    """ListEvents200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListEvents200Response:
        """Test ListEvents200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListEvents200Response`
        """
        model = ListEvents200Response()
        if include_optional:
            return ListEvents200Response(
                data = [
                    lomi_sdk.models.events.events(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        customer_id = '', 
                        event_data = lomi_sdk.models.event_data.event_data(), 
                        event_id = '', 
                        event_name = '', 
                        metadata = lomi_sdk.models.metadata.metadata(), 
                        organization_id = '', 
                        product_id = '', )
                    ],
                pagination = lomi_sdk.models.list_customers_200_response_pagination.listCustomers_200_response_pagination(
                    limit = 56, 
                    offset = 56, 
                    total = 56, )
            )
        else:
            return ListEvents200Response(
        )
        """

    def testListEvents200Response(self):
        """Test ListEvents200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
