# coding: utf-8

"""
    lomi. API

    Payment processing API for francophone West African businesses.

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi.api.beneficiary_payouts_api import BeneficiaryPayoutsApi


class TestBeneficiaryPayoutsApi(unittest.TestCase):
    """BeneficiaryPayoutsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BeneficiaryPayoutsApi()

    def tearDown(self) -> None:
        pass

    def test_create_beneficiary_payout(self) -> None:
        """Test case for create_beneficiary_payout

        Create beneficiary payout
        """
        pass

    def test_list_beneficiary_payouts(self) -> None:
        """Test case for list_beneficiary_payouts

        List beneficiary payouts
        """
        pass

    def test_retrieve_beneficiary_payout(self) -> None:
        """Test case for retrieve_beneficiary_payout

        Retrieve beneficiary payout
        """
        pass


if __name__ == '__main__':
    unittest.main()
