# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.models.webhook_delivery_logs import WebhookDeliveryLogs

class TestWebhookDeliveryLogs(unittest.TestCase):
    """WebhookDeliveryLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveryLogs:
        """Test WebhookDeliveryLogs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveryLogs`
        """
        model = WebhookDeliveryLogs()
        if include_optional:
            return WebhookDeliveryLogs(
                attempt_number = 1.337,
                compte_paye = '',
                compte_payeur = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                event_type = '',
                headers = None,
                ip_address = '',
                log_id = '',
                montant = 1.337,
                organization_id = '',
                payload = None,
                request_duration_ms = 1.337,
                response_body = '',
                response_status = 1.337,
                spi_event_code = '',
                spi_tx_id = '',
                success = True,
                user_agent = '',
                webhook_id = ''
            )
        else:
            return WebhookDeliveryLogs(
        )
        """

    def testWebhookDeliveryLogs(self):
        """Test WebhookDeliveryLogs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
