# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.models.payment_requests_get200_response import PaymentRequestsGet200Response

class TestPaymentRequestsGet200Response(unittest.TestCase):
    """PaymentRequestsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRequestsGet200Response:
        """Test PaymentRequestsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRequestsGet200Response`
        """
        model = PaymentRequestsGet200Response()
        if include_optional:
            return PaymentRequestsGet200Response(
                data = [
                    lomi_sdk.models.payment_requests.payment_requests(
                        amount = 1.337, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        currency_code = '', 
                        customer_id = '', 
                        description = '', 
                        environment = '', 
                        expiry_date = '', 
                        organization_id = '', 
                        payment_link = '', 
                        payment_reference = '', 
                        request_id = '', 
                        spi_account_number = '', 
                        spi_bulk_instruction_id = '', 
                        spi_confirmation = True, 
                        spi_date_envoi = '', 
                        spi_date_irrevocabilite = '', 
                        spi_date_limite_paiement = '', 
                        spi_date_limite_reponse = '', 
                        spi_date_rejet = '', 
                        spi_debit_differe = True, 
                        spi_end2end_id = '', 
                        spi_payeur_alias = '', 
                        spi_payeur_nom = '', 
                        spi_payeur_pays = '', 
                        spi_payment_request_category = '', 
                        spi_payment_status = '', 
                        spi_ref_doc_numero = '', 
                        spi_ref_doc_type = '', 
                        spi_rejection_reason = '', 
                        spi_remise_amount = 1.337, 
                        spi_remise_rate = 1.337, 
                        spi_tx_id = '', 
                        status = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = lomi_sdk.models._customers_get_200_response_pagination._customers_get_200_response_pagination(
                    limit = 56, 
                    offset = 56, 
                    total = 56, )
            )
        else:
            return PaymentRequestsGet200Response(
        )
        """

    def testPaymentRequestsGet200Response(self):
        """Test PaymentRequestsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
