# coding: utf-8

"""
    lomi. API

    Payment processing API for francophone West African businesses.

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi.api.meter_balances_api import MeterBalancesApi


class TestMeterBalancesApi(unittest.TestCase):
    """MeterBalancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeterBalancesApi()

    def tearDown(self) -> None:
        pass

    def test_list_meter_balances(self) -> None:
        """Test case for list_meter_balances

        List meter balances
        """
        pass

    def test_retrieve_meter_balance(self) -> None:
        """Test case for retrieve_meter_balance

        Retrieve meter balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
