# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.api.webhook_api import WebhookApi


class TestWebhookApi(unittest.TestCase):
    """WebhookApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhookApi()

    def tearDown(self) -> None:
        pass

    def test_webhooks_get(self) -> None:
        """Test case for webhooks_get

        List webhooks
        """
        pass

    def test_webhooks_post(self) -> None:
        """Test case for webhooks_post

        Create webhook
        """
        pass

    def test_webhooks_webhook_id_delete(self) -> None:
        """Test case for webhooks_webhook_id_delete

        Delete webhook
        """
        pass

    def test_webhooks_webhook_id_get(self) -> None:
        """Test case for webhooks_webhook_id_get

        Get webhook
        """
        pass

    def test_webhooks_webhook_id_patch(self) -> None:
        """Test case for webhooks_webhook_id_patch

        Update webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
