# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.models.spi_qr_codes_update import SpiQrCodesUpdate

class TestSpiQrCodesUpdate(unittest.TestCase):
    """SpiQrCodesUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpiQrCodesUpdate:
        """Test SpiQrCodesUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpiQrCodesUpdate`
        """
        model = SpiQrCodesUpdate()
        if include_optional:
            return SpiQrCodesUpdate(
                categorie = '',
                checkout_session_id = '',
                compte_paye = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                environment = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_active = True,
                is_used = True,
                metadata = None,
                montant = 1.337,
                name = '',
                organization_id = '',
                payeur_alias = '',
                payment_request_id = '',
                plan_id = '',
                product_id = '',
                qr_code_data = '',
                qr_code_id = '',
                qr_code_image_data = '',
                qr_code_image_url = '',
                qr_code_type = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SpiQrCodesUpdate(
        )
        """

    def testSpiQrCodesUpdate(self):
        """Test SpiQrCodesUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
