# coding: utf-8

"""
    lomi. API

    # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lomi_sdk.api.payouts_api import PayoutsApi


class TestPayoutsApi(unittest.TestCase):
    """PayoutsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayoutsApi()

    def tearDown(self) -> None:
        pass

    def test_create_beneficiary_payout(self) -> None:
        """Test case for create_beneficiary_payout

        Create beneficiary payout
        """
        pass

    def test_create_payout(self) -> None:
        """Test case for create_payout

        Create payout
        """
        pass

    def test_delete_payout(self) -> None:
        """Test case for delete_payout

        Delete payout
        """
        pass

    def test_list_beneficiary_payouts(self) -> None:
        """Test case for list_beneficiary_payouts

        List beneficiary payouts
        """
        pass

    def test_list_payout_methods(self) -> None:
        """Test case for list_payout_methods

        List payout methods
        """
        pass

    def test_list_payouts(self) -> None:
        """Test case for list_payouts

        List payouts
        """
        pass

    def test_retrieve_beneficiary_payout(self) -> None:
        """Test case for retrieve_beneficiary_payout

        Retrieve beneficiary payout
        """
        pass

    def test_retrieve_payout(self) -> None:
        """Test case for retrieve_payout

        Retrieve payout
        """
        pass

    def test_retrieve_payout_method(self) -> None:
        """Test case for retrieve_payout_method

        Retrieve payout method
        """
        pass

    def test_update_payout(self) -> None:
        """Test case for update_payout

        Update payout
        """
        pass


if __name__ == '__main__':
    unittest.main()
