<?php
/**
 * ProductTypeEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lomi. API
 *
 * Payment processing API for francophone West African businesses.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: hello@lomi.africa
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LomiSDK\Model;
use \LomiSDK\ObjectSerializer;

/**
 * ProductTypeEnum Class Doc Comment
 *
 * @category Class
 * @description Enum: product_type_enum
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductTypeEnum
{
    /**
     * Possible values of this enum
     */
    public const ONE_TIME = 'one_time';

    public const RECURRING = 'recurring';

    public const USAGE_BASED = 'usage_based';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ONE_TIME,
            self::RECURRING,
            self::USAGE_BASED
        ];
    }
}


