<?php
/**
 * Transactions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lomi. API
 *
 * Payment processing API for francophone West African businesses.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: hello@lomi.africa
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LomiSDK\Model;

use \ArrayAccess;
use \LomiSDK\ObjectSerializer;

/**
 * Transactions Class Doc Comment
 *
 * @category Class
 * @description transactions resource object
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Transactions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'transactions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'checkout_session_id' => 'string',
        'created_at' => '\DateTime',
        'currency_code' => 'string',
        'customer_id' => 'string',
        'description' => 'string',
        'discount_amount' => 'float',
        'environment' => 'string',
        'fee_amount' => 'float',
        'fee_structure_id' => 'string',
        'gross_amount' => 'float',
        'is_bnpl' => 'bool',
        'is_pos' => 'bool',
        'metadata' => 'object',
        'net_amount' => 'float',
        'organization_id' => 'string',
        'payment_method_code' => 'string',
        'price_id' => 'string',
        'product_id' => 'string',
        'provider_code' => 'string',
        'quantity' => 'float',
        'spi_account_number' => 'string',
        'spi_bulk_instruction_id' => 'string',
        'spi_date_envoi' => 'string',
        'spi_date_irrevocabilite' => 'string',
        'spi_discount_amount' => 'float',
        'spi_discount_rate' => 'float',
        'spi_end2end_id' => 'string',
        'spi_payment_category' => 'string',
        'spi_payment_flow_type' => 'string',
        'spi_payment_status' => 'string',
        'spi_rejection_reason' => 'string',
        'spi_tx_id' => 'string',
        'status' => 'string',
        'subscription_id' => 'string',
        'transaction_id' => 'string',
        'transaction_type' => 'string',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'checkout_session_id' => 'uuid',
        'created_at' => 'date-time',
        'currency_code' => null,
        'customer_id' => 'uuid',
        'description' => null,
        'discount_amount' => 'double',
        'environment' => null,
        'fee_amount' => 'double',
        'fee_structure_id' => 'uuid',
        'gross_amount' => 'double',
        'is_bnpl' => null,
        'is_pos' => null,
        'metadata' => null,
        'net_amount' => 'double',
        'organization_id' => 'uuid',
        'payment_method_code' => null,
        'price_id' => 'uuid',
        'product_id' => 'uuid',
        'provider_code' => null,
        'quantity' => 'double',
        'spi_account_number' => null,
        'spi_bulk_instruction_id' => 'uuid',
        'spi_date_envoi' => null,
        'spi_date_irrevocabilite' => null,
        'spi_discount_amount' => 'double',
        'spi_discount_rate' => 'double',
        'spi_end2end_id' => 'uuid',
        'spi_payment_category' => null,
        'spi_payment_flow_type' => null,
        'spi_payment_status' => null,
        'spi_rejection_reason' => null,
        'spi_tx_id' => 'uuid',
        'status' => null,
        'subscription_id' => 'uuid',
        'transaction_id' => 'uuid',
        'transaction_type' => null,
        'updated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'checkout_session_id' => false,
        'created_at' => false,
        'currency_code' => false,
        'customer_id' => false,
        'description' => false,
        'discount_amount' => false,
        'environment' => false,
        'fee_amount' => false,
        'fee_structure_id' => false,
        'gross_amount' => false,
        'is_bnpl' => false,
        'is_pos' => false,
        'metadata' => false,
        'net_amount' => false,
        'organization_id' => false,
        'payment_method_code' => false,
        'price_id' => false,
        'product_id' => false,
        'provider_code' => false,
        'quantity' => false,
        'spi_account_number' => false,
        'spi_bulk_instruction_id' => false,
        'spi_date_envoi' => false,
        'spi_date_irrevocabilite' => false,
        'spi_discount_amount' => false,
        'spi_discount_rate' => false,
        'spi_end2end_id' => false,
        'spi_payment_category' => false,
        'spi_payment_flow_type' => false,
        'spi_payment_status' => false,
        'spi_rejection_reason' => false,
        'spi_tx_id' => false,
        'status' => false,
        'subscription_id' => false,
        'transaction_id' => false,
        'transaction_type' => false,
        'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'checkout_session_id' => 'checkout_session_id',
        'created_at' => 'created_at',
        'currency_code' => 'currency_code',
        'customer_id' => 'customer_id',
        'description' => 'description',
        'discount_amount' => 'discount_amount',
        'environment' => 'environment',
        'fee_amount' => 'fee_amount',
        'fee_structure_id' => 'fee_structure_id',
        'gross_amount' => 'gross_amount',
        'is_bnpl' => 'is_bnpl',
        'is_pos' => 'is_pos',
        'metadata' => 'metadata',
        'net_amount' => 'net_amount',
        'organization_id' => 'organization_id',
        'payment_method_code' => 'payment_method_code',
        'price_id' => 'price_id',
        'product_id' => 'product_id',
        'provider_code' => 'provider_code',
        'quantity' => 'quantity',
        'spi_account_number' => 'spi_account_number',
        'spi_bulk_instruction_id' => 'spi_bulk_instruction_id',
        'spi_date_envoi' => 'spi_date_envoi',
        'spi_date_irrevocabilite' => 'spi_date_irrevocabilite',
        'spi_discount_amount' => 'spi_discount_amount',
        'spi_discount_rate' => 'spi_discount_rate',
        'spi_end2end_id' => 'spi_end2end_id',
        'spi_payment_category' => 'spi_payment_category',
        'spi_payment_flow_type' => 'spi_payment_flow_type',
        'spi_payment_status' => 'spi_payment_status',
        'spi_rejection_reason' => 'spi_rejection_reason',
        'spi_tx_id' => 'spi_tx_id',
        'status' => 'status',
        'subscription_id' => 'subscription_id',
        'transaction_id' => 'transaction_id',
        'transaction_type' => 'transaction_type',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'checkout_session_id' => 'setCheckoutSessionId',
        'created_at' => 'setCreatedAt',
        'currency_code' => 'setCurrencyCode',
        'customer_id' => 'setCustomerId',
        'description' => 'setDescription',
        'discount_amount' => 'setDiscountAmount',
        'environment' => 'setEnvironment',
        'fee_amount' => 'setFeeAmount',
        'fee_structure_id' => 'setFeeStructureId',
        'gross_amount' => 'setGrossAmount',
        'is_bnpl' => 'setIsBnpl',
        'is_pos' => 'setIsPos',
        'metadata' => 'setMetadata',
        'net_amount' => 'setNetAmount',
        'organization_id' => 'setOrganizationId',
        'payment_method_code' => 'setPaymentMethodCode',
        'price_id' => 'setPriceId',
        'product_id' => 'setProductId',
        'provider_code' => 'setProviderCode',
        'quantity' => 'setQuantity',
        'spi_account_number' => 'setSpiAccountNumber',
        'spi_bulk_instruction_id' => 'setSpiBulkInstructionId',
        'spi_date_envoi' => 'setSpiDateEnvoi',
        'spi_date_irrevocabilite' => 'setSpiDateIrrevocabilite',
        'spi_discount_amount' => 'setSpiDiscountAmount',
        'spi_discount_rate' => 'setSpiDiscountRate',
        'spi_end2end_id' => 'setSpiEnd2endId',
        'spi_payment_category' => 'setSpiPaymentCategory',
        'spi_payment_flow_type' => 'setSpiPaymentFlowType',
        'spi_payment_status' => 'setSpiPaymentStatus',
        'spi_rejection_reason' => 'setSpiRejectionReason',
        'spi_tx_id' => 'setSpiTxId',
        'status' => 'setStatus',
        'subscription_id' => 'setSubscriptionId',
        'transaction_id' => 'setTransactionId',
        'transaction_type' => 'setTransactionType',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'checkout_session_id' => 'getCheckoutSessionId',
        'created_at' => 'getCreatedAt',
        'currency_code' => 'getCurrencyCode',
        'customer_id' => 'getCustomerId',
        'description' => 'getDescription',
        'discount_amount' => 'getDiscountAmount',
        'environment' => 'getEnvironment',
        'fee_amount' => 'getFeeAmount',
        'fee_structure_id' => 'getFeeStructureId',
        'gross_amount' => 'getGrossAmount',
        'is_bnpl' => 'getIsBnpl',
        'is_pos' => 'getIsPos',
        'metadata' => 'getMetadata',
        'net_amount' => 'getNetAmount',
        'organization_id' => 'getOrganizationId',
        'payment_method_code' => 'getPaymentMethodCode',
        'price_id' => 'getPriceId',
        'product_id' => 'getProductId',
        'provider_code' => 'getProviderCode',
        'quantity' => 'getQuantity',
        'spi_account_number' => 'getSpiAccountNumber',
        'spi_bulk_instruction_id' => 'getSpiBulkInstructionId',
        'spi_date_envoi' => 'getSpiDateEnvoi',
        'spi_date_irrevocabilite' => 'getSpiDateIrrevocabilite',
        'spi_discount_amount' => 'getSpiDiscountAmount',
        'spi_discount_rate' => 'getSpiDiscountRate',
        'spi_end2end_id' => 'getSpiEnd2endId',
        'spi_payment_category' => 'getSpiPaymentCategory',
        'spi_payment_flow_type' => 'getSpiPaymentFlowType',
        'spi_payment_status' => 'getSpiPaymentStatus',
        'spi_rejection_reason' => 'getSpiRejectionReason',
        'spi_tx_id' => 'getSpiTxId',
        'status' => 'getStatus',
        'subscription_id' => 'getSubscriptionId',
        'transaction_id' => 'getTransactionId',
        'transaction_type' => 'getTransactionType',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('checkout_session_id', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('customer_id', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('discount_amount', $data ?? [], null);
        $this->setIfExists('environment', $data ?? [], null);
        $this->setIfExists('fee_amount', $data ?? [], null);
        $this->setIfExists('fee_structure_id', $data ?? [], null);
        $this->setIfExists('gross_amount', $data ?? [], null);
        $this->setIfExists('is_bnpl', $data ?? [], null);
        $this->setIfExists('is_pos', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('net_amount', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('payment_method_code', $data ?? [], null);
        $this->setIfExists('price_id', $data ?? [], null);
        $this->setIfExists('product_id', $data ?? [], null);
        $this->setIfExists('provider_code', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('spi_account_number', $data ?? [], null);
        $this->setIfExists('spi_bulk_instruction_id', $data ?? [], null);
        $this->setIfExists('spi_date_envoi', $data ?? [], null);
        $this->setIfExists('spi_date_irrevocabilite', $data ?? [], null);
        $this->setIfExists('spi_discount_amount', $data ?? [], null);
        $this->setIfExists('spi_discount_rate', $data ?? [], null);
        $this->setIfExists('spi_end2end_id', $data ?? [], null);
        $this->setIfExists('spi_payment_category', $data ?? [], null);
        $this->setIfExists('spi_payment_flow_type', $data ?? [], null);
        $this->setIfExists('spi_payment_status', $data ?? [], null);
        $this->setIfExists('spi_rejection_reason', $data ?? [], null);
        $this->setIfExists('spi_tx_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('subscription_id', $data ?? [], null);
        $this->setIfExists('transaction_id', $data ?? [], null);
        $this->setIfExists('transaction_type', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets checkout_session_id
     *
     * @return string|null
     */
    public function getCheckoutSessionId()
    {
        return $this->container['checkout_session_id'];
    }

    /**
     * Sets checkout_session_id
     *
     * @param string|null $checkout_session_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setCheckoutSessionId($checkout_session_id)
    {
        if (is_null($checkout_session_id)) {
            throw new \InvalidArgumentException('non-nullable checkout_session_id cannot be null');
        }
        $this->container['checkout_session_id'] = $checkout_session_id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at ISO 8601 datetime
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code Three-letter ISO currency code (e.g., XOF, USD, EUR)
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        if (is_null($currency_code)) {
            throw new \InvalidArgumentException('non-nullable currency_code cannot be null');
        }
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (is_null($customer_id)) {
            throw new \InvalidArgumentException('non-nullable customer_id cannot be null');
        }
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets discount_amount
     *
     * @return float|null
     */
    public function getDiscountAmount()
    {
        return $this->container['discount_amount'];
    }

    /**
     * Sets discount_amount
     *
     * @param float|null $discount_amount discount_amount
     *
     * @return self
     */
    public function setDiscountAmount($discount_amount)
    {
        if (is_null($discount_amount)) {
            throw new \InvalidArgumentException('non-nullable discount_amount cannot be null');
        }
        $this->container['discount_amount'] = $discount_amount;

        return $this;
    }

    /**
     * Gets environment
     *
     * @return string|null
     */
    public function getEnvironment()
    {
        return $this->container['environment'];
    }

    /**
     * Sets environment
     *
     * @param string|null $environment environment
     *
     * @return self
     */
    public function setEnvironment($environment)
    {
        if (is_null($environment)) {
            throw new \InvalidArgumentException('non-nullable environment cannot be null');
        }
        $this->container['environment'] = $environment;

        return $this;
    }

    /**
     * Gets fee_amount
     *
     * @return float|null
     */
    public function getFeeAmount()
    {
        return $this->container['fee_amount'];
    }

    /**
     * Sets fee_amount
     *
     * @param float|null $fee_amount fee_amount
     *
     * @return self
     */
    public function setFeeAmount($fee_amount)
    {
        if (is_null($fee_amount)) {
            throw new \InvalidArgumentException('non-nullable fee_amount cannot be null');
        }
        $this->container['fee_amount'] = $fee_amount;

        return $this;
    }

    /**
     * Gets fee_structure_id
     *
     * @return string|null
     */
    public function getFeeStructureId()
    {
        return $this->container['fee_structure_id'];
    }

    /**
     * Sets fee_structure_id
     *
     * @param string|null $fee_structure_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setFeeStructureId($fee_structure_id)
    {
        if (is_null($fee_structure_id)) {
            throw new \InvalidArgumentException('non-nullable fee_structure_id cannot be null');
        }
        $this->container['fee_structure_id'] = $fee_structure_id;

        return $this;
    }

    /**
     * Gets gross_amount
     *
     * @return float|null
     */
    public function getGrossAmount()
    {
        return $this->container['gross_amount'];
    }

    /**
     * Sets gross_amount
     *
     * @param float|null $gross_amount gross_amount
     *
     * @return self
     */
    public function setGrossAmount($gross_amount)
    {
        if (is_null($gross_amount)) {
            throw new \InvalidArgumentException('non-nullable gross_amount cannot be null');
        }
        $this->container['gross_amount'] = $gross_amount;

        return $this;
    }

    /**
     * Gets is_bnpl
     *
     * @return bool|null
     */
    public function getIsBnpl()
    {
        return $this->container['is_bnpl'];
    }

    /**
     * Sets is_bnpl
     *
     * @param bool|null $is_bnpl is_bnpl
     *
     * @return self
     */
    public function setIsBnpl($is_bnpl)
    {
        if (is_null($is_bnpl)) {
            throw new \InvalidArgumentException('non-nullable is_bnpl cannot be null');
        }
        $this->container['is_bnpl'] = $is_bnpl;

        return $this;
    }

    /**
     * Gets is_pos
     *
     * @return bool|null
     */
    public function getIsPos()
    {
        return $this->container['is_pos'];
    }

    /**
     * Sets is_pos
     *
     * @param bool|null $is_pos is_pos
     *
     * @return self
     */
    public function setIsPos($is_pos)
    {
        if (is_null($is_pos)) {
            throw new \InvalidArgumentException('non-nullable is_pos cannot be null');
        }
        $this->container['is_pos'] = $is_pos;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return object|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param object|null $metadata Set of key-value pairs for storing additional information
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets net_amount
     *
     * @return float|null
     */
    public function getNetAmount()
    {
        return $this->container['net_amount'];
    }

    /**
     * Sets net_amount
     *
     * @param float|null $net_amount net_amount
     *
     * @return self
     */
    public function setNetAmount($net_amount)
    {
        if (is_null($net_amount)) {
            throw new \InvalidArgumentException('non-nullable net_amount cannot be null');
        }
        $this->container['net_amount'] = $net_amount;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string|null
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string|null $organization_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets payment_method_code
     *
     * @return string|null
     */
    public function getPaymentMethodCode()
    {
        return $this->container['payment_method_code'];
    }

    /**
     * Sets payment_method_code
     *
     * @param string|null $payment_method_code payment_method_code
     *
     * @return self
     */
    public function setPaymentMethodCode($payment_method_code)
    {
        if (is_null($payment_method_code)) {
            throw new \InvalidArgumentException('non-nullable payment_method_code cannot be null');
        }
        $this->container['payment_method_code'] = $payment_method_code;

        return $this;
    }

    /**
     * Gets price_id
     *
     * @return string|null
     */
    public function getPriceId()
    {
        return $this->container['price_id'];
    }

    /**
     * Sets price_id
     *
     * @param string|null $price_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setPriceId($price_id)
    {
        if (is_null($price_id)) {
            throw new \InvalidArgumentException('non-nullable price_id cannot be null');
        }
        $this->container['price_id'] = $price_id;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string|null
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string|null $product_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setProductId($product_id)
    {
        if (is_null($product_id)) {
            throw new \InvalidArgumentException('non-nullable product_id cannot be null');
        }
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets provider_code
     *
     * @return string|null
     */
    public function getProviderCode()
    {
        return $this->container['provider_code'];
    }

    /**
     * Sets provider_code
     *
     * @param string|null $provider_code provider_code
     *
     * @return self
     */
    public function setProviderCode($provider_code)
    {
        if (is_null($provider_code)) {
            throw new \InvalidArgumentException('non-nullable provider_code cannot be null');
        }
        $this->container['provider_code'] = $provider_code;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets spi_account_number
     *
     * @return string|null
     */
    public function getSpiAccountNumber()
    {
        return $this->container['spi_account_number'];
    }

    /**
     * Sets spi_account_number
     *
     * @param string|null $spi_account_number spi_account_number
     *
     * @return self
     */
    public function setSpiAccountNumber($spi_account_number)
    {
        if (is_null($spi_account_number)) {
            throw new \InvalidArgumentException('non-nullable spi_account_number cannot be null');
        }
        $this->container['spi_account_number'] = $spi_account_number;

        return $this;
    }

    /**
     * Gets spi_bulk_instruction_id
     *
     * @return string|null
     */
    public function getSpiBulkInstructionId()
    {
        return $this->container['spi_bulk_instruction_id'];
    }

    /**
     * Sets spi_bulk_instruction_id
     *
     * @param string|null $spi_bulk_instruction_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setSpiBulkInstructionId($spi_bulk_instruction_id)
    {
        if (is_null($spi_bulk_instruction_id)) {
            throw new \InvalidArgumentException('non-nullable spi_bulk_instruction_id cannot be null');
        }
        $this->container['spi_bulk_instruction_id'] = $spi_bulk_instruction_id;

        return $this;
    }

    /**
     * Gets spi_date_envoi
     *
     * @return string|null
     */
    public function getSpiDateEnvoi()
    {
        return $this->container['spi_date_envoi'];
    }

    /**
     * Sets spi_date_envoi
     *
     * @param string|null $spi_date_envoi spi_date_envoi
     *
     * @return self
     */
    public function setSpiDateEnvoi($spi_date_envoi)
    {
        if (is_null($spi_date_envoi)) {
            throw new \InvalidArgumentException('non-nullable spi_date_envoi cannot be null');
        }
        $this->container['spi_date_envoi'] = $spi_date_envoi;

        return $this;
    }

    /**
     * Gets spi_date_irrevocabilite
     *
     * @return string|null
     */
    public function getSpiDateIrrevocabilite()
    {
        return $this->container['spi_date_irrevocabilite'];
    }

    /**
     * Sets spi_date_irrevocabilite
     *
     * @param string|null $spi_date_irrevocabilite spi_date_irrevocabilite
     *
     * @return self
     */
    public function setSpiDateIrrevocabilite($spi_date_irrevocabilite)
    {
        if (is_null($spi_date_irrevocabilite)) {
            throw new \InvalidArgumentException('non-nullable spi_date_irrevocabilite cannot be null');
        }
        $this->container['spi_date_irrevocabilite'] = $spi_date_irrevocabilite;

        return $this;
    }

    /**
     * Gets spi_discount_amount
     *
     * @return float|null
     */
    public function getSpiDiscountAmount()
    {
        return $this->container['spi_discount_amount'];
    }

    /**
     * Sets spi_discount_amount
     *
     * @param float|null $spi_discount_amount spi_discount_amount
     *
     * @return self
     */
    public function setSpiDiscountAmount($spi_discount_amount)
    {
        if (is_null($spi_discount_amount)) {
            throw new \InvalidArgumentException('non-nullable spi_discount_amount cannot be null');
        }
        $this->container['spi_discount_amount'] = $spi_discount_amount;

        return $this;
    }

    /**
     * Gets spi_discount_rate
     *
     * @return float|null
     */
    public function getSpiDiscountRate()
    {
        return $this->container['spi_discount_rate'];
    }

    /**
     * Sets spi_discount_rate
     *
     * @param float|null $spi_discount_rate spi_discount_rate
     *
     * @return self
     */
    public function setSpiDiscountRate($spi_discount_rate)
    {
        if (is_null($spi_discount_rate)) {
            throw new \InvalidArgumentException('non-nullable spi_discount_rate cannot be null');
        }
        $this->container['spi_discount_rate'] = $spi_discount_rate;

        return $this;
    }

    /**
     * Gets spi_end2end_id
     *
     * @return string|null
     */
    public function getSpiEnd2endId()
    {
        return $this->container['spi_end2end_id'];
    }

    /**
     * Sets spi_end2end_id
     *
     * @param string|null $spi_end2end_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setSpiEnd2endId($spi_end2end_id)
    {
        if (is_null($spi_end2end_id)) {
            throw new \InvalidArgumentException('non-nullable spi_end2end_id cannot be null');
        }
        $this->container['spi_end2end_id'] = $spi_end2end_id;

        return $this;
    }

    /**
     * Gets spi_payment_category
     *
     * @return string|null
     */
    public function getSpiPaymentCategory()
    {
        return $this->container['spi_payment_category'];
    }

    /**
     * Sets spi_payment_category
     *
     * @param string|null $spi_payment_category spi_payment_category
     *
     * @return self
     */
    public function setSpiPaymentCategory($spi_payment_category)
    {
        if (is_null($spi_payment_category)) {
            throw new \InvalidArgumentException('non-nullable spi_payment_category cannot be null');
        }
        $this->container['spi_payment_category'] = $spi_payment_category;

        return $this;
    }

    /**
     * Gets spi_payment_flow_type
     *
     * @return string|null
     */
    public function getSpiPaymentFlowType()
    {
        return $this->container['spi_payment_flow_type'];
    }

    /**
     * Sets spi_payment_flow_type
     *
     * @param string|null $spi_payment_flow_type spi_payment_flow_type
     *
     * @return self
     */
    public function setSpiPaymentFlowType($spi_payment_flow_type)
    {
        if (is_null($spi_payment_flow_type)) {
            throw new \InvalidArgumentException('non-nullable spi_payment_flow_type cannot be null');
        }
        $this->container['spi_payment_flow_type'] = $spi_payment_flow_type;

        return $this;
    }

    /**
     * Gets spi_payment_status
     *
     * @return string|null
     */
    public function getSpiPaymentStatus()
    {
        return $this->container['spi_payment_status'];
    }

    /**
     * Sets spi_payment_status
     *
     * @param string|null $spi_payment_status spi_payment_status
     *
     * @return self
     */
    public function setSpiPaymentStatus($spi_payment_status)
    {
        if (is_null($spi_payment_status)) {
            throw new \InvalidArgumentException('non-nullable spi_payment_status cannot be null');
        }
        $this->container['spi_payment_status'] = $spi_payment_status;

        return $this;
    }

    /**
     * Gets spi_rejection_reason
     *
     * @return string|null
     */
    public function getSpiRejectionReason()
    {
        return $this->container['spi_rejection_reason'];
    }

    /**
     * Sets spi_rejection_reason
     *
     * @param string|null $spi_rejection_reason spi_rejection_reason
     *
     * @return self
     */
    public function setSpiRejectionReason($spi_rejection_reason)
    {
        if (is_null($spi_rejection_reason)) {
            throw new \InvalidArgumentException('non-nullable spi_rejection_reason cannot be null');
        }
        $this->container['spi_rejection_reason'] = $spi_rejection_reason;

        return $this;
    }

    /**
     * Gets spi_tx_id
     *
     * @return string|null
     */
    public function getSpiTxId()
    {
        return $this->container['spi_tx_id'];
    }

    /**
     * Sets spi_tx_id
     *
     * @param string|null $spi_tx_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setSpiTxId($spi_tx_id)
    {
        if (is_null($spi_tx_id)) {
            throw new \InvalidArgumentException('non-nullable spi_tx_id cannot be null');
        }
        $this->container['spi_tx_id'] = $spi_tx_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Current status of the resource
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets subscription_id
     *
     * @return string|null
     */
    public function getSubscriptionId()
    {
        return $this->container['subscription_id'];
    }

    /**
     * Sets subscription_id
     *
     * @param string|null $subscription_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setSubscriptionId($subscription_id)
    {
        if (is_null($subscription_id)) {
            throw new \InvalidArgumentException('non-nullable subscription_id cannot be null');
        }
        $this->container['subscription_id'] = $subscription_id;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return string|null
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string|null $transaction_id Unique identifier (UUID format)
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        if (is_null($transaction_id)) {
            throw new \InvalidArgumentException('non-nullable transaction_id cannot be null');
        }
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets transaction_type
     *
     * @return string|null
     */
    public function getTransactionType()
    {
        return $this->container['transaction_type'];
    }

    /**
     * Sets transaction_type
     *
     * @param string|null $transaction_type transaction_type
     *
     * @return self
     */
    public function setTransactionType($transaction_type)
    {
        if (is_null($transaction_type)) {
            throw new \InvalidArgumentException('non-nullable transaction_type cannot be null');
        }
        $this->container['transaction_type'] = $transaction_type;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at ISO 8601 datetime
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


