<?php
/**
 * WebhookEvent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lomi. API
 *
 * Payment processing API for francophone West African businesses.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: hello@lomi.africa
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LomiSDK\Model;
use \LomiSDK\ObjectSerializer;

/**
 * WebhookEvent Class Doc Comment
 *
 * @category Class
 * @description Enum: webhook_event
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookEvent
{
    /**
     * Possible values of this enum
     */
    public const PAYMENT_CREATED = 'PAYMENT_CREATED';

    public const PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED';

    public const PAYMENT_FAILED = 'PAYMENT_FAILED';

    public const PAYMENT_CANCELED = 'PAYMENT_CANCELED';

    public const REFUND_CREATED = 'REFUND_CREATED';

    public const REFUND_COMPLETED = 'REFUND_COMPLETED';

    public const REFUND_FAILED = 'REFUND_FAILED';

    public const SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED';

    public const SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED';

    public const SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED';

    public const CHECKOUT_COMPLETED = 'CHECKOUT_COMPLETED';

    public const PROVIDER_STATUS_CHANGED = 'PROVIDER_STATUS_CHANGED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYMENT_CREATED,
            self::PAYMENT_SUCCEEDED,
            self::PAYMENT_FAILED,
            self::PAYMENT_CANCELED,
            self::REFUND_CREATED,
            self::REFUND_COMPLETED,
            self::REFUND_FAILED,
            self::SUBSCRIPTION_CREATED,
            self::SUBSCRIPTION_RENEWED,
            self::SUBSCRIPTION_CANCELED,
            self::CHECKOUT_COMPLETED,
            self::PROVIDER_STATUS_CHANGED
        ];
    }
}


