<?php
/**
 * EventsUpdateTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LomiSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lomi. API
 *
 * # lomi. API  The lomi. API provides a comprehensive payment processing platform for francophone WestAfrican businesses.  ## Authentication  All API requests require authentication using an API key. Include your API key in the `X-API-KEY` header.  ```bash curl https://api.lomi.africa/v1/customers \\   -H \"X-API-KEY: your_api_key_here\" ```  ## Rate limiting  API requests are rate-limited based on your plan. Rate limit headers are included in all responses.  ## Webhooks  Configure webhooks to receive real-time notifications about events in your account.  ## Environments  - **Live**: Production environment with real transactions - **Test**: Sandbox environment for development and testing
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: hello@lomi.africa
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LomiSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EventsUpdateTest Class Doc Comment
 *
 * @category    Class
 * @description Update events input
 * @package     LomiSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EventsUpdateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EventsUpdate"
     */
    public function testEventsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_data"
     */
    public function testPropertyEventData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
