# coding: utf-8

"""
    lomi. API

    Payment processing API for francophone West African businesses.

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CustomersCreate(BaseModel):
    """
    Request body for creating a customers object. System-managed fields like `created_at`, `organization_id`, and IDs are automatically set.
    """ # noqa: E501
    address: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    email: Optional[StrictStr] = Field(default=None, description="Email address")
    is_business: Optional[StrictBool] = None
    is_deleted: Optional[StrictBool] = Field(default=None, description="Soft deletion flag")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Set of key-value pairs for storing additional information")
    name: Optional[StrictStr] = None
    phone_number: Optional[StrictStr] = None
    postal_code: Optional[StrictStr] = None
    spi_alias_mbno: Optional[StrictStr] = None
    spi_alias_shid: Optional[StrictStr] = None
    spi_primary_alias: Optional[StrictStr] = None
    whatsapp_number: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "city", "country", "email", "is_business", "is_deleted", "metadata", "name", "phone_number", "postal_code", "spi_alias_mbno", "spi_alias_shid", "spi_primary_alias", "whatsapp_number"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomersCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomersCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "city": obj.get("city"),
            "country": obj.get("country"),
            "email": obj.get("email"),
            "is_business": obj.get("is_business"),
            "is_deleted": obj.get("is_deleted"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name"),
            "phone_number": obj.get("phone_number"),
            "postal_code": obj.get("postal_code"),
            "spi_alias_mbno": obj.get("spi_alias_mbno"),
            "spi_alias_shid": obj.get("spi_alias_shid"),
            "spi_primary_alias": obj.get("spi_primary_alias"),
            "whatsapp_number": obj.get("whatsapp_number")
        })
        return _obj


