# coding: utf-8

"""
    lomi. API

    Payment processing API for francophone West African businesses.

    The version of the OpenAPI document: 1.1.0
    Contact: hello@lomi.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class Webhooks(BaseModel):
    """
    webhooks resource object
    """ # noqa: E501
    authorized_events: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, description="ISO 8601 datetime")
    created_by: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = Field(default=None, description="ISO 8601 datetime")
    environment: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = Field(default=None, description="Whether this resource is currently active")
    last_payload: Optional[Dict[str, Any]] = None
    last_response_body: Optional[StrictStr] = None
    last_response_status: Optional[Union[StrictFloat, StrictInt]] = None
    last_triggered_at: Optional[datetime] = Field(default=None, description="ISO 8601 datetime")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Set of key-value pairs for storing additional information")
    organization_id: Optional[UUID] = Field(default=None, description="Unique identifier (UUID format)")
    retry_count: Optional[Union[StrictFloat, StrictInt]] = None
    spi_event_types: Optional[StrictStr] = None
    supports_spi: Optional[StrictBool] = None
    updated_at: Optional[datetime] = Field(default=None, description="ISO 8601 datetime")
    url: Optional[StrictStr] = Field(default=None, description="URL/URI")
    verification_token: Optional[StrictStr] = None
    webhook_id: Optional[UUID] = Field(default=None, description="Unique identifier (UUID format)")
    __properties: ClassVar[List[str]] = ["authorized_events", "created_at", "created_by", "deleted_at", "environment", "is_active", "last_payload", "last_response_body", "last_response_status", "last_triggered_at", "metadata", "organization_id", "retry_count", "spi_event_types", "supports_spi", "updated_at", "url", "verification_token", "webhook_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Webhooks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "created_by",
            "deleted_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Webhooks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authorized_events": obj.get("authorized_events"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "deleted_at": obj.get("deleted_at"),
            "environment": obj.get("environment"),
            "is_active": obj.get("is_active"),
            "last_payload": obj.get("last_payload"),
            "last_response_body": obj.get("last_response_body"),
            "last_response_status": obj.get("last_response_status"),
            "last_triggered_at": obj.get("last_triggered_at"),
            "metadata": obj.get("metadata"),
            "organization_id": obj.get("organization_id"),
            "retry_count": obj.get("retry_count"),
            "spi_event_types": obj.get("spi_event_types"),
            "supports_spi": obj.get("supports_spi"),
            "updated_at": obj.get("updated_at"),
            "url": obj.get("url"),
            "verification_token": obj.get("verification_token"),
            "webhook_id": obj.get("webhook_id")
        })
        return _obj


